export type Profession = "obecné" | "truhlář" | "zedník" | "instalatér" | "elektrikář" | "číšník" | "kuchař" | "pokladní" | "uklízečka" | "sestřička" | "kancelář" | "automechanik" | "zahradník";

export interface ProfessionInfo {
  id: Profession;
  label: string;
  emoji: string;
  group: "řemesla" | "gastro" | "zdravotnictví" | "obchod" | "úklid" | "kancelář" | "obecné" | "doprava" | "zemědělství";
}

export const PROFESSION_LIST: ProfessionInfo[] = [
  { id: "kancelář", label: "Kancelář", emoji: "🏢", group: "kancelář" },
  { id: "truhlář", label: "Truhlář", emoji: "🪚", group: "řemesla" },
  { id: "zedník", label: "Zedník", emoji: "🧱", group: "řemesla" },
  { id: "instalatér", label: "Instalatér", emoji: "🔧", group: "řemesla" },
  { id: "elektrikář", label: "Elektrikář", emoji: "⚡", group: "řemesla" },
  { id: "kuchař", label: "Kuchař", emoji: "👨‍🍳", group: "gastro" },
  { id: "číšník", label: "Číšník", emoji: "🍽️", group: "gastro" },
  { id: "pokladní", label: "Pokladní", emoji: "🛒", group: "obchod" },
  { id: "sestřička", label: "Sestřička", emoji: "🏥", group: "zdravotnictví" },
  { id: "uklízečka", label: "Uklízečka", emoji: "🧹", group: "úklid" },
  { id: "automechanik", label: "Automechanik", emoji: "🚗", group: "doprava" },
  { id: "zahradník", label: "Zahradník", emoji: "🌱", group: "zemědělství" },
];

export interface Question {
  text: string;
  options: string[];
  correct: number;
  translation: string;
  profession: Profession;
}

export interface FillQuestion {
  sentence: string;
  answer: string;
  translation: string;
  profession: Profession;
}

export const QUESTIONS: Question[] = [
  // === OBECNÉ (základy) ===
  { text: "Jaký člen má Lama?", options: ["der", "die", "das"], correct: 2, translation: "lama", profession: "obecné" },
  { text: "Jaký člen má Haus?", options: ["der", "die", "das"], correct: 2, translation: "dům", profession: "obecné" },
  { text: "Jaký člen má Hund?", options: ["der", "die", "das"], correct: 0, translation: "pes", profession: "obecné" },
  { text: "Jaký člen má Katze?", options: ["der", "die", "das"], correct: 1, translation: "kočka", profession: "obecné" },
  { text: "Jaký člen má Buch?", options: ["der", "die", "das"], correct: 2, translation: "kniha", profession: "obecné" },
  { text: "Jaký člen má Tisch?", options: ["der", "die", "das"], correct: 0, translation: "stůl", profession: "obecné" },
  { text: "Jaký člen má Blume?", options: ["der", "die", "das"], correct: 1, translation: "květina", profession: "obecné" },
  { text: "Jaký člen má Auto?", options: ["der", "die", "das"], correct: 2, translation: "auto", profession: "automechanik" },
  { text: "Jaký člen má Baum?", options: ["der", "die", "das"], correct: 0, translation: "strom", profession: "obecné" },
  { text: "Jaký člen má Schule?", options: ["der", "die", "das"], correct: 1, translation: "škola", profession: "obecné" },
  // === KANCELÁŘ ===
  { text: "Jaký člen má Schreibtisch?", options: ["der", "die", "das"], correct: 0, translation: "psací stůl", profession: "kancelář" },
  { text: "Jaký člen má Stuhl?", options: ["der", "die", "das"], correct: 0, translation: "židle", profession: "kancelář" },
  { text: "Jaký člen má Computer?", options: ["der", "die", "das"], correct: 0, translation: "počítač", profession: "kancelář" },
  { text: "Jaký člen má Monitor?", options: ["der", "die", "das"], correct: 0, translation: "monitor", profession: "kancelář" },
  { text: "Jaký člen má Tastatur?", options: ["der", "die", "das"], correct: 1, translation: "klávesnice", profession: "kancelář" },
  { text: "Jaký člen má Maus?", options: ["der", "die", "das"], correct: 1, translation: "myš", profession: "kancelář" },
  { text: "Jaký člen má Dokument?", options: ["der", "die", "das"], correct: 2, translation: "dokument", profession: "kancelář" },
  { text: "Jaký člen má Formular?", options: ["der", "die", "das"], correct: 2, translation: "formulář", profession: "kancelář" },
  { text: "Jaký člen má Büro?", options: ["der", "die", "das"], correct: 2, translation: "kancelář", profession: "kancelář" },
  { text: "Jaký člen má Drucker?", options: ["der", "die", "das"], correct: 0, translation: "tiskárna", profession: "kancelář" },
  { text: "Jaký člen má Scanner?", options: ["der", "die", "das"], correct: 0, translation: "skener", profession: "kancelář" },
  { text: "Jaký člen má Kopierer?", options: ["der", "die", "das"], correct: 0, translation: "kopírka", profession: "kancelář" },
  { text: "Jaký člen má Aktenschrank?", options: ["der", "die", "das"], correct: 0, translation: "kartotéka", profession: "kancelář" },
  { text: "Jaký člen má Regal?", options: ["der", "die", "das"], correct: 2, translation: "regál", profession: "kancelář" },
  { text: "Jaký člen má Telefon?", options: ["der", "die", "das"], correct: 2, translation: "telefon", profession: "kancelář" },
  { text: "Jaký člen má E-Mail?", options: ["der", "die", "das"], correct: 1, translation: "e-mail", profession: "kancelář" },
  { text: "Jaký člen má Besprechung?", options: ["der", "die", "das"], correct: 1, translation: "porada", profession: "kancelář" },
  { text: "Jaký člen má Notebook?", options: ["der", "die", "das"], correct: 2, translation: "notebook", profession: "kancelář" },
  { text: "Jaký člen má Papierkorb?", options: ["der", "die", "das"], correct: 0, translation: "koš", profession: "kancelář" },
  { text: "Jaký člen má Whiteboard?", options: ["der", "die", "das"], correct: 2, translation: "tabule", profession: "kancelář" },
  { text: "Jaký člen má Chef?", options: ["der", "die", "das"], correct: 0, translation: "šéf", profession: "kancelář" },
  { text: "Jaký člen má Kollegin?", options: ["der", "die", "das"], correct: 1, translation: "kolegyně", profession: "kancelář" },
  { text: "Jaký člen má Kollege?", options: ["der", "die", "das"], correct: 0, translation: "kolega", profession: "kancelář" },
  { text: "Jaký člen má Meeting?", options: ["der", "die", "das"], correct: 2, translation: "schůzka", profession: "kancelář" },
  { text: "Jaký člen má Projektor?", options: ["der", "die", "das"], correct: 0, translation: "projektor", profession: "kancelář" },
  { text: "Jaký člen má Präsentation?", options: ["der", "die", "das"], correct: 1, translation: "prezentace", profession: "kancelář" },
  { text: "Jaký člen má Einladung?", options: ["der", "die", "das"], correct: 1, translation: "pozvánka", profession: "kancelář" },
  { text: "Jaký člen má Termin?", options: ["der", "die", "das"], correct: 0, translation: "termín", profession: "kancelář" },
  { text: "Jaký člen má Homeoffice?", options: ["der", "die", "das"], correct: 2, translation: "home office", profession: "kancelář" },
  { text: "Jaký člen má Entscheidung?", options: ["der", "die", "das"], correct: 1, translation: "rozhodnutí", profession: "kancelář" },
  { text: "Jaký člen má Projekt?", options: ["der", "die", "das"], correct: 2, translation: "projekt", profession: "kancelář" },
  { text: "Jaký člen má Priorität?", options: ["der", "die", "das"], correct: 1, translation: "priorita", profession: "kancelář" },
  { text: "Jaký člen má Feedback?", options: ["der", "die", "das"], correct: 2, translation: "zpětná vazba", profession: "kancelář" },
  { text: "Jaký člen má Entwurf?", options: ["der", "die", "das"], correct: 0, translation: "návrh", profession: "kancelář" },
  { text: "Jaký člen má Status?", options: ["der", "die", "das"], correct: 0, translation: "stav", profession: "kancelář" },
  { text: "Jaký člen má Kosten?", options: ["der", "die", "das"], correct: 1, translation: "náklady", profession: "kancelář" },
  { text: "Jaký člen má Team?", options: ["der", "die", "das"], correct: 2, translation: "tým", profession: "kancelář" },
  { text: "Jaký člen má Unterlagen?", options: ["der", "die", "das"], correct: 1, translation: "podklady", profession: "kancelář" },
  { text: "Jaký člen má Deadline?", options: ["der", "die", "das"], correct: 1, translation: "termín (uzávěrka)", profession: "kancelář" },
  { text: "Jaký člen má Zusammenarbeit?", options: ["der", "die", "das"], correct: 1, translation: "spolupráce", profession: "kancelář" },
  // === OBECNÉ (práce, směny, bezpečnost) ===
  { text: "Jaký člen má Pause?", options: ["der", "die", "das"], correct: 1, translation: "přestávka", profession: "obecné" },
  { text: "Jaký člen má Kantine?", options: ["der", "die", "das"], correct: 1, translation: "jídelna", profession: "obecné" },
  { text: "Jaký člen má Schrank?", options: ["der", "die", "das"], correct: 0, translation: "skříň", profession: "obecné" },
  { text: "Jaký člen má Tür?", options: ["der", "die", "das"], correct: 1, translation: "dveře", profession: "obecné" },
  { text: "Jaký člen má Fenster?", options: ["der", "die", "das"], correct: 2, translation: "okno", profession: "obecné" },
  { text: "Jaký člen má Lampe?", options: ["der", "die", "das"], correct: 1, translation: "lampa", profession: "obecné" },
  { text: "Jaký člen má WC?", options: ["der", "die", "das"], correct: 2, translation: "záchod", profession: "obecné" },
  { text: "Jaký člen má Umkleide?", options: ["der", "die", "das"], correct: 1, translation: "šatna", profession: "obecné" },
  { text: "Jaký člen má Schicht?", options: ["der", "die", "das"], correct: 1, translation: "směna", profession: "obecné" },
  { text: "Jaký člen má Frühschicht?", options: ["der", "die", "das"], correct: 1, translation: "ranní směna", profession: "obecné" },
  { text: "Jaký člen má Spätschicht?", options: ["der", "die", "das"], correct: 1, translation: "odpolední směna", profession: "obecné" },
  { text: "Jaký člen má Nachtschicht?", options: ["der", "die", "das"], correct: 1, translation: "noční směna", profession: "obecné" },
  { text: "Jaký člen má Tagschicht?", options: ["der", "die", "das"], correct: 1, translation: "denní směna", profession: "obecné" },
  { text: "Jaký člen má Schichtplan?", options: ["der", "die", "das"], correct: 0, translation: "plán směn", profession: "obecné" },
  { text: "Jaký člen má Arbeitszeit?", options: ["der", "die", "das"], correct: 1, translation: "pracovní doba", profession: "obecné" },
  { text: "Jaký člen má Teilzeit?", options: ["der", "die", "das"], correct: 1, translation: "zkrácený úvazek", profession: "obecné" },
  { text: "Jaký člen má Vollzeit?", options: ["der", "die", "das"], correct: 1, translation: "plný úvazek", profession: "obecné" },
  { text: "Jaký člen má Gleitzeit?", options: ["der", "die", "das"], correct: 1, translation: "pružná pracovní doba", profession: "obecné" },
  { text: "Jaký člen má Dienstplan?", options: ["der", "die", "das"], correct: 0, translation: "rozpis služeb", profession: "obecné" },
  { text: "Jaký člen má Urlaub?", options: ["der", "die", "das"], correct: 0, translation: "dovolená", profession: "obecné" },
  { text: "Jaký člen má Feiertag?", options: ["der", "die", "das"], correct: 0, translation: "svátek", profession: "obecné" },
  { text: "Jaký člen má Krankmeldung?", options: ["der", "die", "das"], correct: 1, translation: "nahlášení nemoci", profession: "obecné" },
  { text: "Jaký člen má Vertretung?", options: ["der", "die", "das"], correct: 1, translation: "zástup", profession: "obecné" },
  { text: "Jaký člen má Spind?", options: ["der", "die", "das"], correct: 0, translation: "skříňka", profession: "obecné" },
  { text: "Jaký člen má Erste Hilfe?", options: ["der", "die", "das"], correct: 1, translation: "první pomoc", profession: "obecné" },
  { text: "Jaký člen má Feuerlöscher?", options: ["der", "die", "das"], correct: 0, translation: "hasicí přístroj", profession: "obecné" },
  { text: "Jaký člen má Unfall?", options: ["der", "die", "das"], correct: 0, translation: "úraz", profession: "obecné" },
  { text: "Jaký člen má Warnweste?", options: ["der", "die", "das"], correct: 1, translation: "výstražná vesta", profession: "obecné" },
  { text: "Jaký člen má Schutzbrille?", options: ["der", "die", "das"], correct: 1, translation: "ochranné brýle", profession: "obecné" },
  { text: "Jaký člen má Vorschrift?", options: ["der", "die", "das"], correct: 1, translation: "předpis", profession: "obecné" },
  { text: "Jaký člen má Sicherheit?", options: ["der", "die", "das"], correct: 1, translation: "bezpečnost", profession: "obecné" },
  { text: "Jaký člen má Fließband?", options: ["der", "die", "das"], correct: 2, translation: "výrobní pás", profession: "obecné" },
  { text: "Jaký člen má Reparatur?", options: ["der", "die", "das"], correct: 1, translation: "oprava", profession: "obecné" },
  { text: "Jaký člen má Störung?", options: ["der", "die", "das"], correct: 1, translation: "porucha", profession: "obecné" },
  { text: "Jaký člen má Defekt?", options: ["der", "die", "das"], correct: 0, translation: "závada", profession: "obecné" },
  { text: "Jaký člen má Schraube?", options: ["der", "die", "das"], correct: 1, translation: "šroub", profession: "obecné" },
  { text: "Jaký člen má Bohrmaschine?", options: ["der", "die", "das"], correct: 1, translation: "vrtačka", profession: "obecné" },
  { text: "Jaký člen má Qualität?", options: ["der", "die", "das"], correct: 1, translation: "kvalita", profession: "obecné" },
  { text: "Jaký člen má Material?", options: ["der", "die", "das"], correct: 2, translation: "materiál", profession: "obecné" },
  { text: "Jaký člen má Sicherheitsschuhe?", options: ["der", "die", "das"], correct: 1, translation: "bezpečnostní boty", profession: "obecné" },
  { text: "Jaký člen má Werkstatt?", options: ["der", "die", "das"], correct: 1, translation: "dílna", profession: "obecné" },
  { text: "Jaký člen má Moment?", options: ["der", "die", "das"], correct: 0, translation: "moment / chvilka", profession: "obecné" },
  { text: "Jaký člen má Zeit?", options: ["der", "die", "das"], correct: 1, translation: "čas", profession: "obecné" },
  { text: "Jaký člen má Maschine?", options: ["der", "die", "das"], correct: 1, translation: "stroj", profession: "obecné" },
  { text: "Jaký člen má Teil?", options: ["der", "die", "das"], correct: 2, translation: "díl / součástka", profession: "obecné" },
  { text: "Jaký člen má Förderband?", options: ["der", "die", "das"], correct: 2, translation: "dopravní pás", profession: "obecné" },
  { text: "Jaký člen má Quote?", options: ["der", "die", "das"], correct: 1, translation: "kvóta", profession: "obecné" },
  { text: "Jaký člen má Stunde?", options: ["der", "die", "das"], correct: 1, translation: "hodina", profession: "obecné" },
  { text: "Jaký člen má Schichtbetrieb?", options: ["der", "die", "das"], correct: 0, translation: "směnný provoz", profession: "obecné" },
  { text: "Jaký člen má Schutzkleidung?", options: ["der", "die", "das"], correct: 1, translation: "ochranný oděv", profession: "obecné" },
  { text: "Jaký člen má Werkzeuge?", options: ["der", "die", "das"], correct: 1, translation: "nářadí", profession: "obecné" },
  { text: "Jaký člen má Helm?", options: ["der", "die", "das"], correct: 0, translation: "helma", profession: "zedník" },
  { text: "Jaký člen má Hammer?", options: ["der", "die", "das"], correct: 0, translation: "kladivo", profession: "zedník" },
  // === TRUHLÁŘ ===
  { text: "Jaký člen má Brett?", options: ["der", "die", "das"], correct: 2, translation: "deska / prkno", profession: "truhlář" },
  { text: "Jaký člen má Eichenholz?", options: ["der", "die", "das"], correct: 2, translation: "dubové dřevo", profession: "truhlář" },
  { text: "Jaký člen má Holz?", options: ["der", "die", "das"], correct: 2, translation: "dřevo", profession: "truhlář" },
  { text: "Jaký člen má Verarbeitung?", options: ["der", "die", "das"], correct: 1, translation: "zpracování", profession: "truhlář" },
  { text: "Jaký člen má Kanten?", options: ["der", "die", "das"], correct: 1, translation: "hrany", profession: "truhlář" },
  { text: "Jaký člen má Säge?", options: ["der", "die", "das"], correct: 1, translation: "pila", profession: "truhlář" },
   { text: "Jaký člen má Leim?", options: ["der", "die", "das"], correct: 0, translation: "lepidlo", profession: "truhlář" },
   // === AUTOMECHANIK ===
   { text: "Jaký člen má Motor?", options: ["der", "die", "das"], correct: 0, translation: "motor", profession: "automechanik" },
   { text: "Jaký člen má Bremse?", options: ["der", "die", "das"], correct: 1, translation: "brzda", profession: "automechanik" },
   { text: "Jaký člen má Reifen?", options: ["der", "die", "das"], correct: 0, translation: "pneumatika", profession: "automechanik" },
   { text: "Jaký člen má Werkzeug?", options: ["der", "die", "das"], correct: 2, translation: "nářadí", profession: "automechanik" },
   // === ZEDNÍK ===
  { text: "Jaký člen má Gerüst?", options: ["der", "die", "das"], correct: 2, translation: "lešení", profession: "zedník" },
  { text: "Jaký člen má Zement?", options: ["der", "die", "das"], correct: 0, translation: "cement", profession: "zedník" },
  { text: "Jaký člen má Pläne?", options: ["der", "die", "das"], correct: 1, translation: "plány", profession: "zedník" },
  { text: "Jaký člen má Erdgeschoss?", options: ["der", "die", "das"], correct: 2, translation: "přízemí", profession: "zedník" },
  { text: "Jaký člen má Mörtel?", options: ["der", "die", "das"], correct: 0, translation: "malta", profession: "zedník" },
  { text: "Jaký člen má Mauer?", options: ["der", "die", "das"], correct: 1, translation: "zeď", profession: "zedník" },
  { text: "Jaký člen má Baustelle?", options: ["der", "die", "das"], correct: 1, translation: "stavba (místo)", profession: "zedník" },
  // === SESTŘIČKA ===
  { text: "Jaký člen má Patient?", options: ["der", "die", "das"], correct: 0, translation: "pacient", profession: "sestřička" },
  { text: "Jaký člen má Fieber?", options: ["der", "die", "das"], correct: 2, translation: "teplota / horečka", profession: "sestřička" },
  { text: "Jaký člen má Medikamente?", options: ["der", "die", "das"], correct: 1, translation: "léky", profession: "sestřička" },
  { text: "Jaký člen má Blut?", options: ["der", "die", "das"], correct: 2, translation: "krev", profession: "sestřička" },
  { text: "Jaký člen má Schmerzen?", options: ["der", "die", "das"], correct: 1, translation: "bolesti", profession: "sestřička" },
  { text: "Jaký člen má Schwindel?", options: ["der", "die", "das"], correct: 0, translation: "závrať", profession: "sestřička" },
  { text: "Jaký člen má Arzt?", options: ["der", "die", "das"], correct: 0, translation: "lékař", profession: "sestřička" },
  { text: "Jaký člen má Visite?", options: ["der", "die", "das"], correct: 1, translation: "vizita", profession: "sestřička" },
  // === KUCHAŘ ===
  { text: "Jaký člen má Tagesmenü?", options: ["der", "die", "das"], correct: 2, translation: "denní menu", profession: "kuchař" },
  { text: "Jaký člen má Gericht?", options: ["der", "die", "das"], correct: 2, translation: "jídlo / pokrm", profession: "kuchař" },
  { text: "Jaký člen má Fleisch?", options: ["der", "die", "das"], correct: 2, translation: "maso", profession: "kuchař" },
  { text: "Jaký člen má Messer?", options: ["der", "die", "das"], correct: 2, translation: "nůž", profession: "kuchař" },
  { text: "Jaký člen má Pfanne?", options: ["der", "die", "das"], correct: 1, translation: "pánev", profession: "kuchař" },
  { text: "Jaký člen má Kochtopf?", options: ["der", "die", "das"], correct: 0, translation: "hrnec", profession: "kuchař" },
  { text: "Jaký člen má Suppe?", options: ["der", "die", "das"], correct: 1, translation: "polévka", profession: "kuchař" },
  { text: "Jaký člen má Kräuter?", options: ["der", "die", "das"], correct: 1, translation: "bylinky", profession: "kuchař" },
  { text: "Jaký člen má Soße?", options: ["der", "die", "das"], correct: 1, translation: "omáčka", profession: "kuchař" },
  { text: "Jaký člen má Gemüse?", options: ["der", "die", "das"], correct: 2, translation: "zelenina", profession: "kuchař" },
  { text: "Jaký člen má Kühlraum?", options: ["der", "die", "das"], correct: 0, translation: "chladicí místnost / box", profession: "kuchař" },
  { text: "Jaký člen má Knoblauch?", options: ["der", "die", "das"], correct: 0, translation: "česnek", profession: "kuchař" },
  { text: "Jaký člen má Küchenchef?", options: ["der", "die", "das"], correct: 0, translation: "šéfkuchař", profession: "kuchař" },
  { text: "Jaký člen má Vorspeise?", options: ["der", "die", "das"], correct: 1, translation: "předkrm", profession: "kuchař" },
  { text: "Jaký člen má Hauptgericht?", options: ["der", "die", "das"], correct: 2, translation: "hlavní chod", profession: "kuchař" },
  // === ČÍŠNÍK ===
  { text: "Jaký člen má Teller?", options: ["der", "die", "das"], correct: 0, translation: "talíř", profession: "číšník" },
  { text: "Jaký člen má Nachtisch?", options: ["der", "die", "das"], correct: 0, translation: "dezert", profession: "číšník" },
  { text: "Jaký člen má Besteck?", options: ["der", "die", "das"], correct: 2, translation: "příbor", profession: "číšník" },
  { text: "Jaký člen má Glas?", options: ["der", "die", "das"], correct: 2, translation: "sklenice", profession: "číšník" },
  { text: "Jaký člen má Serviette?", options: ["der", "die", "das"], correct: 1, translation: "ubrousek", profession: "číšník" },
  { text: "Jaký člen má Tischdecke?", options: ["der", "die", "das"], correct: 1, translation: "ubrus", profession: "číšník" },
  { text: "Jaký člen má Trinkgeld?", options: ["der", "die", "das"], correct: 2, translation: "spropitné", profession: "číšník" },
  { text: "Jaký člen má Allergie?", options: ["der", "die", "das"], correct: 1, translation: "alergie", profession: "číšník" },
  { text: "Jaký člen má Bier?", options: ["der", "die", "das"], correct: 2, translation: "pivo", profession: "číšník" },
  { text: "Jaký člen má Speisekarte?", options: ["der", "die", "das"], correct: 1, translation: "jídelní lístek", profession: "číšník" },
  { text: "Jaký člen má Rechnung?", options: ["der", "die", "das"], correct: 1, translation: "účet / faktura", profession: "číšník" },
  // === POKLADNÍ ===
  { text: "Jaký člen má Kasse?", options: ["der", "die", "das"], correct: 1, translation: "pokladna", profession: "pokladní" },
  { text: "Jaký člen má Kassenbon?", options: ["der", "die", "das"], correct: 0, translation: "účtenka", profession: "pokladní" },
  { text: "Jaký člen má Kundenkarte?", options: ["der", "die", "das"], correct: 1, translation: "zákaznická karta", profession: "pokladní" },
  { text: "Jaký člen má Wechselgeld?", options: ["der", "die", "das"], correct: 2, translation: "peníze nazpět", profession: "pokladní" },
  { text: "Jaký člen má Kleingeld?", options: ["der", "die", "das"], correct: 2, translation: "drobné", profession: "pokladní" },
  { text: "Jaký člen má Einkaufswagen?", options: ["der", "die", "das"], correct: 0, translation: "nákupní vozík", profession: "pokladní" },
  { text: "Jaký člen má Einkaufskorb?", options: ["der", "die", "das"], correct: 0, translation: "nákupní košík", profession: "pokladní" },
  { text: "Jaký člen má Ware?", options: ["der", "die", "das"], correct: 1, translation: "zboží", profession: "pokladní" },
  { text: "Jaký člen má Angebot?", options: ["der", "die", "das"], correct: 2, translation: "nabídka / akce", profession: "pokladní" },
  { text: "Jaký člen má Rabatt?", options: ["der", "die", "das"], correct: 0, translation: "sleva", profession: "pokladní" },
  { text: "Jaký člen má Tüte?", options: ["der", "die", "das"], correct: 1, translation: "taška (igelitová/papírová)", profession: "pokladní" },
  { text: "Jaký člen má Pfand?", options: ["der", "die", "das"], correct: 2, translation: "záloha (za láhve)", profession: "pokladní" },
  { text: "Jaký člen má Tiefkühlkost?", options: ["der", "die", "das"], correct: 1, translation: "mražené potraviny", profession: "pokladní" },
  { text: "Jaký člen má Molkereiprodukte?", options: ["der", "die", "das"], correct: 1, translation: "mléčné výrobky", profession: "pokladní" },
  { text: "Jaký člen má Bäckerei?", options: ["der", "die", "das"], correct: 1, translation: "pekařství", profession: "pokladní" },
  { text: "Jaký člen má Haltbarkeitsdatum?", options: ["der", "die", "das"], correct: 2, translation: "datum trvanlivosti", profession: "pokladní" },
  { text: "Jaký člen má Barcode?", options: ["der", "die", "das"], correct: 0, translation: "čárový kód", profession: "pokladní" },
  { text: "Jaký člen má Lager?", options: ["der", "die", "das"], correct: 2, translation: "sklad", profession: "pokladní" },
  { text: "Jaký člen má Kunde?", options: ["der", "die", "das"], correct: 0, translation: "zákazník", profession: "pokladní" },
  // === UKLÍZEČKA ===
  { text: "Jaký člen má Staubsauger?", options: ["der", "die", "das"], correct: 0, translation: "vysavač", profession: "uklízečka" },
  { text: "Jaký člen má Wischer?", options: ["der", "die", "das"], correct: 0, translation: "mop / stěrač", profession: "uklízečka" },
  { text: "Jaký člen má Reinigungsmittel?", options: ["der", "die", "das"], correct: 2, translation: "čisticí prostředek", profession: "uklízečka" },
  { text: "Jaký člen má Eimer?", options: ["der", "die", "das"], correct: 0, translation: "kýbl", profession: "uklízečka" },
  { text: "Jaký člen má Lappen?", options: ["der", "die", "das"], correct: 0, translation: "hadr", profession: "uklízečka" },
  { text: "Jaký člen má Besen?", options: ["der", "die", "das"], correct: 0, translation: "koště", profession: "uklízečka" },
  { text: "Jaký člen má Staub?", options: ["der", "die", "das"], correct: 0, translation: "prach", profession: "uklízečka" },
  { text: "Jaký člen má Müll?", options: ["der", "die", "das"], correct: 0, translation: "odpadky", profession: "uklízečka" },
  { text: "Jaký člen má Mülltonne?", options: ["der", "die", "das"], correct: 1, translation: "popelnice", profession: "uklízečka" },
  { text: "Jaký člen má Fensterleder?", options: ["der", "die", "das"], correct: 2, translation: "jelenice na okna", profession: "uklízečka" },
  { text: "Jaký člen má Schwamm?", options: ["der", "die", "das"], correct: 0, translation: "houbička", profession: "uklízečka" },
  { text: "Jaký člen má Waschbecken?", options: ["der", "die", "das"], correct: 2, translation: "umyvadlo", profession: "uklízečka" },
  { text: "Jaký člen má Toilette?", options: ["der", "die", "das"], correct: 1, translation: "toaleta", profession: "uklízečka" },
  { text: "Jaký člen má Treppenhaus?", options: ["der", "die", "das"], correct: 2, translation: "schodiště", profession: "uklízečka" },
  { text: "Jaký člen má Stock?", options: ["der", "die", "das"], correct: 0, translation: "patro", profession: "uklízečka" },
  { text: "Jaký člen má Seife?", options: ["der", "die", "das"], correct: 1, translation: "mýdlo", profession: "uklízečka" },
  { text: "Jaký člen má Toilettenpapier?", options: ["der", "die", "das"], correct: 2, translation: "toaletní papír", profession: "uklízečka" },
  { text: "Jaký člen má Schmutz?", options: ["der", "die", "das"], correct: 0, translation: "špína", profession: "uklízečka" },
  { text: "Jaký člen má Besprechungsraum?", options: ["der", "die", "das"], correct: 0, translation: "jednací místnost", profession: "uklízečka" },
  { text: "Jaký člen má Handschuhe?", options: ["der", "die", "das"], correct: 1, translation: "rukavice", profession: "uklízečka" },
];

export const FILL_QUESTIONS: FillQuestion[] = [
  // === OBECNÉ (základy) ===
  { sentence: "Ich ___ Deutsch.", answer: "spreche", translation: "Já mluvím německy.", profession: "obecné" },
  { sentence: "Er ___ ein Buch.", answer: "liest", translation: "On čte knihu.", profession: "obecné" },
  { sentence: "Wir ___ nach Hause.", answer: "gehen", translation: "My jdeme domů.", profession: "obecné" },
  { sentence: "Sie ___ Kaffee.", answer: "trinkt", translation: "Ona pije kávu.", profession: "obecné" },
  { sentence: "Du ___ sehr schnell.", answer: "läufst", translation: "Ty běžíš velmi rychle.", profession: "obecné" },
  { sentence: "Ich ___ müde.", answer: "bin", translation: "Já jsem unavený/á.", profession: "obecné" },
  { sentence: "Er ___ Lehrer.", answer: "ist", translation: "On je učitel.", profession: "obecné" },
  { sentence: "Wir ___ Studenten.", answer: "sind", translation: "My jsme studenti.", profession: "obecné" },
  { sentence: "Sie ___ eine Katze.", answer: "hat", translation: "Ona má kočku.", profession: "obecné" },
  { sentence: "Du ___ Hunger.", answer: "hast", translation: "Ty máš hlad.", profession: "obecné" },
  { sentence: "Ich ___ gern Musik.", answer: "höre", translation: "Já rád/a poslouchám hudbu.", profession: "obecné" },
  { sentence: "Er ___ Fußball.", answer: "spielt", translation: "On hraje fotbal.", profession: "obecné" },
  { sentence: "Wir ___ ins Kino.", answer: "gehen", translation: "My jdeme do kina.", profession: "obecné" },
  { sentence: "Sie ___ sehr gut.", answer: "kocht", translation: "Ona vaří velmi dobře.", profession: "obecné" },
  { sentence: "Du ___ schön.", answer: "singst", translation: "Ty zpíváš krásně.", profession: "obecné" },
  { sentence: "Ich ___ Wasser.", answer: "trinke", translation: "Já piji vodu.", profession: "obecné" },
  { sentence: "Er ___ die Tür.", answer: "öffnet", translation: "On otevírá dveře.", profession: "obecné" },
  { sentence: "Wir ___ Deutsch.", answer: "lernen", translation: "My se učíme německy.", profession: "obecné" },
  { sentence: "Sie ___ das Fenster.", answer: "schließt", translation: "Ona zavírá okno.", profession: "obecné" },
  { sentence: "Du ___ mir.", answer: "hilfst", translation: "Ty mi pomáháš.", profession: "obecné" },
  // === OBECNÉ (práce, bezpečnost) ===
  { sentence: "Wann ___ du an zu arbeiten?", answer: "fängst", translation: "Kdy začínáš pracovat?", profession: "obecné" },
  { sentence: "Hast du heute viel ___?", answer: "Arbeit", translation: "Máš dnes hodně práce?", profession: "obecné" },
  { sentence: "Kannst du mir damit ___?", answer: "helfen", translation: "Můžeš mi s tím pomoct?", profession: "obecné" },
  { sentence: "Wer ist dafür ___?", answer: "verantwortlich", translation: "Kdo je za to zodpovědný?", profession: "obecné" },
  { sentence: "Ich ___ mehr Zeit.", answer: "brauche", translation: "Potřebuji více času.", profession: "obecné" },
  { sentence: "Das ist nicht meine ___.", answer: "Verantwortung", translation: "To není moje zodpovědnost.", profession: "obecné" },
  { sentence: "Ich habe einen Fehler ___.", answer: "gemacht", translation: "Udělal jsem chybu.", profession: "obecné" },
  { sentence: "Wo sind die ___?", answer: "Schutzhandschuhe", translation: "Kde jsou ochranné rukavice?", profession: "obecné" },
  { sentence: "Muss ich eine Schutzbrille ___?", answer: "tragen", translation: "Musím nosit ochranné brýle?", profession: "obecné" },
  { sentence: "Das ist ___.", answer: "gefährlich", translation: "To je nebezpečné.", profession: "obecné" },
  { sentence: "___ auf!", answer: "Pass", translation: "Dávej pozor!", profession: "obecné" },
  { sentence: "Die Maschine ist ___.", answer: "kaputt", translation: "Ten stroj je rozbitý.", profession: "obecné" },
  { sentence: "Wer ist für die Sicherheit ___?", answer: "verantwortlich", translation: "Kdo je zodpovědný za bezpečnost?", profession: "obecné" },
  { sentence: "Wir sollten das ___.", answer: "melden", translation: "Měli bychom to nahlásit.", profession: "obecné" },
  { sentence: "Ich brauche eine ___.", answer: "Sicherheitsschulung", translation: "Potřebuji bezpečnostní školení.", profession: "obecné" },
  { sentence: "Kannst du die Maschine ___?", answer: "ausschalten", translation: "Můžeš vypnout ten stroj?", profession: "obecné" },
  { sentence: "Kannst du mir das ___?", answer: "erklären", translation: "Můžeš mi to vysvětlit?", profession: "obecné" },
  { sentence: "Ich bin nicht deiner ___.", answer: "Meinung", translation: "Nesouhlasím s tebou.", profession: "obecné" },
  { sentence: "Das ist keine gute ___.", answer: "Idee", translation: "To není dobrý nápad.", profession: "obecné" },
  { sentence: "Hast du heute ___?", answer: "Zeit", translation: "Máš dnes čas?", profession: "obecné" },
  { sentence: "Machen wir das ___?", answer: "zusammen", translation: "Uděláme to společně?", profession: "obecné" },
  { sentence: "Das ist nicht ___.", answer: "fair", translation: "To není fér.", profession: "obecné" },
  { sentence: "Das ist nicht mein ___.", answer: "Problem", translation: "To není můj problém.", profession: "obecné" },
  { sentence: "Können wir eine Lösung ___?", answer: "finden", translation: "Můžeme najít řešení?", profession: "obecné" },
  { sentence: "Warum hast du das ___?", answer: "gemacht", translation: "Proč jsi to udělal?", profession: "obecné" },
  { sentence: "Das war ein ___.", answer: "Missverständnis", translation: "To bylo nedorozumění.", profession: "obecné" },
  { sentence: "Ich habe eine ___.", answer: "Frage", translation: "Mám otázku.", profession: "obecné" },
  { sentence: "Ich brauche ___.", answer: "Urlaub", translation: "Potřebuji dovolenou.", profession: "obecné" },
  { sentence: "Mein Kind ist ___.", answer: "krank", translation: "Moje dítě je nemocné.", profession: "obecné" },
  { sentence: "Ich bin damit nicht ___.", answer: "zufrieden", translation: "Nejsem s tím spokojený.", profession: "obecné" },
  { sentence: "Ich entschuldige mich für den ___.", answer: "Fehler", translation: "Omlouvám se za chybu.", profession: "obecné" },
  { sentence: "Ich bin gleich ___.", answer: "fertig", translation: "Budu hned hotov.", profession: "obecné" },
  { sentence: "Das ist ein technisches ___.", answer: "Problem", translation: "To je technický problém.", profession: "obecné" },
  { sentence: "Ich ___ mich später bei Ihnen.", answer: "melde", translation: "Ozvu se Vám později.", profession: "obecné" },
  { sentence: "Die Maschine muss sofort ___ werden.", answer: "gestoppt", translation: "Ten stroj se musí okamžitě zastavit.", profession: "obecné" },
  { sentence: "___ das Teil auf das Förderband.", answer: "Leg", translation: "Polož ten díl na dopravní pás.", profession: "obecné" },
  { sentence: "Wir müssen die ___ pro Stunde einhalten.", answer: "Quote", translation: "Musíme dodržet kvótu za hodinu.", profession: "obecné" },
  { sentence: "Wir arbeiten im ___.", answer: "Schichtbetrieb", translation: "Pracujeme na směny.", profession: "obecné" },
  { sentence: "Ist die Schutzkleidung ___?", answer: "obligatorisch", translation: "Je ochranný oděv povinný?", profession: "obecné" },
  { sentence: "Die Werkzeuge müssen ___ werden.", answer: "gereinigt", translation: "Nářadí se musí vyčistit.", profession: "obecné" },
  { sentence: "Ich brauche eine kurze ___.", answer: "Pause", translation: "Potřebuji krátkou pauzu.", profession: "obecné" },
  { sentence: "___ Sie bitte die Qualität der Teile.", answer: "Kontrollieren", translation: "Zkontrolujte prosím kvalitu těch dílů.", profession: "obecné" },
  { sentence: "Das Material ist fast leer, wir müssen neues ___.", answer: "bestellen", translation: "Materiál skoro došel, musíme objednat nový.", profession: "obecné" },
  { sentence: "Haben Sie die Sicherheitsschuhe ___?", answer: "angezogen", translation: "Máte obuté bezpečnostní boty?", profession: "obecné" },
  { sentence: "Können Sie mir beim Tragen ___?", answer: "helfen", translation: "Můžete mi pomoci s nošením?", profession: "obecné" },
  { sentence: "Wer hat heute Abend die ___?", answer: "Nachtschicht", translation: "Kdo má dnes večer noční směnu?", profession: "obecné" },
  { sentence: "Wir müssen die Werkstatt sauber ___.", answer: "machen", translation: "Musíme uklidit dílnu.", profession: "obecné" },
  { sentence: "Haben Sie einen Moment ___ für mich?", answer: "Zeit", translation: "Máte na mě chvilku čas?", profession: "obecné" },
  // === KANCELÁŘ ===
  { sentence: "Ich ___ dir die Einladung zum Meeting.", answer: "schicke", translation: "Posílám ti pozvánku na schůzku.", profession: "kancelář" },
  { sentence: "Können wir den Termin ___?", answer: "verschieben", translation: "Můžeme ten termín posunout?", profession: "kancelář" },
  { sentence: "Ich bin heute im ___.", answer: "Homeoffice", translation: "Dnes jsem na home office.", profession: "kancelář" },
  { sentence: "Haben wir dazu schon eine ___?", answer: "Entscheidung", translation: "Máme k tomu už nějaké rozhodnutí?", profession: "kancelář" },
  { sentence: "Ich ___ mich darum.", answer: "kümmere", translation: "Postarám se o to.", profession: "kancelář" },
  { sentence: "Das Projekt hat hohe ___.", answer: "Priorität", translation: "Tento projekt má vysokou prioritu.", profession: "kancelář" },
  { sentence: "___ mir bitte eine kurze E-Mail.", answer: "Schreib", translation: "Napiš mi prosím krátký e-mail.", profession: "kancelář" },
  { sentence: "Ich brauche dein ___ zu diesem Entwurf.", answer: "Feedback", translation: "Potřebuji tvoji zpětnou vazbu k tomuto návrhu.", profession: "kancelář" },
  { sentence: "Wie ist der aktuelle ___?", answer: "Status", translation: "Jaký je aktuální stav?", profession: "kancelář" },
  { sentence: "Wir müssen die Kosten ___.", answer: "senken", translation: "Musíme snížit náklady.", profession: "kancelář" },
  { sentence: "Ich habe eine Frage zur ___.", answer: "Rechnung", translation: "Mám dotaz k faktuře.", profession: "kancelář" },
  { sentence: "Unser Team arbeitet sehr ___.", answer: "effizient", translation: "Náš tým pracuje velmi efektivně.", profession: "kancelář" },
  { sentence: "Kannst du mir die Unterlagen ___?", answer: "schicken", translation: "Můžeš mi poslat ty podklady?", profession: "kancelář" },
  { sentence: "Wir ___ das beim nächsten Mal.", answer: "besprechen", translation: "Probereme to příště.", profession: "kancelář" },
  { sentence: "Die Deadline ist morgen ___.", answer: "Mittag", translation: "Termín (deadline) je zítra v poledne.", profession: "kancelář" },
  { sentence: "Vielen Dank für die gute ___.", answer: "Zusammenarbeit", translation: "Děkuji moc za dobrou spolupráci.", profession: "kancelář" },
  { sentence: "Wo ___ ich das Dokument?", answer: "finde", translation: "Kde najdu ten dokument?", profession: "kancelář" },
  // === TRUHLÁŘ ===
  { sentence: "Dieses Holz ist zu ___ für die Verarbeitung.", answer: "feucht", translation: "Toto dřevo je příliš vlhké na zpracování.", profession: "truhlář" },
  { sentence: "Ich muss die Kanten noch ___.", answer: "schleifen", translation: "Musím ještě zbrousit hrany.", profession: "truhlář" },
  { sentence: "Wo ist die ___ und der Leim?", answer: "Säge", translation: "Kde je pila a lepidlo?", profession: "truhlář" },
  { sentence: "Ich habe das Brett falsch ___.", answer: "zugeschnitten", translation: "Špatně jsem tu desku uřízl.", profession: "truhlář" },
  { sentence: "Der Schrank ist aus massivem ___.", answer: "Eichenholz", translation: "Ta skříň je z masivního dubového dřeva.", profession: "truhlář" },
  // === ZEDNÍK ===
  { sentence: "___ bitte den Mörtel an.", answer: "Misch", translation: "Namíchej prosím maltu.", profession: "zedník" },
  { sentence: "Die Mauer muss genau ___ sein.", answer: "gerade", translation: "Ta zeď musí být přesně rovná.", profession: "zedník" },
  { sentence: "Tragen Sie auf der Baustelle immer einen ___.", answer: "Helm", translation: "Na stavbě noste vždy helmu.", profession: "zedník" },
  { sentence: "Wir bauen heute das ___ auf.", answer: "Gerüst", translation: "Dnes stavíme lešení.", profession: "zedník" },
  { sentence: "Der Zement muss noch zwei Stunden ___.", answer: "trocknen", translation: "Cement musí ještě dvě hodiny schnout.", profession: "zedník" },
  { sentence: "Wo sind die Pläne für das ___?", answer: "Erdgeschoss", translation: "Kde jsou plány pro přízemí?", profession: "zedník" },
  { sentence: "___ Sie mir bitte den Hammer.", answer: "Geben", translation: "Dejte mi prosím to kladivo.", profession: "zedník" },
  // === SESTŘIČKA ===
  { sentence: "Ich muss Ihnen Blut ___.", answer: "abnehmen", translation: "Musím vám odebrat krev.", profession: "sestřička" },
  { sentence: "Haben Sie Schmerzen oder ___?", answer: "Schwindel", translation: "Máte bolesti nebo závratě?", profession: "sestřička" },
  { sentence: "Der Arzt kommt gleich zur ___.", answer: "Visite", translation: "Lékař přijde hned na vizitu.", profession: "sestřička" },
  { sentence: "Ich muss bei diesem Patienten Fieber ___.", answer: "messen", translation: "Musím tomuto pacientovi změřit teplotu.", profession: "sestřička" },
  { sentence: "Haben Sie Ihre Medikamente schon ___?", answer: "genommen", translation: "Už jste si vzal své léky?", profession: "sestřička" },
  { sentence: "Ich ___ Ihnen beim Aufstehen.", answer: "helfe", translation: "Pomůžu vám se vstáváním.", profession: "sestřička" },
  // === KUCHAŘ ===
  { sentence: "Das Messer muss sehr ___ sein.", answer: "scharf", translation: "Ten nůž musí být velmi ostrý.", profession: "kuchař" },
  { sentence: "Ich ___ das Fleisch in der Pfanne.", answer: "brate", translation: "Smažím to maso na pánvi.", profession: "kuchař" },
  { sentence: "Die Suppe schmeckt ein bisschen zu ___.", answer: "salzig", translation: "Ta polévka chutná trochu moc slaně.", profession: "kuchař" },
  { sentence: "Stellen Sie die Teller in den ___.", answer: "Wärmeschrank", translation: "Dejte ty talíře do ohřívací skříně.", profession: "kuchař" },
  { sentence: "Wo sind die frischen ___ für die Soße?", answer: "Kräuter", translation: "Kde jsou čerstvé bylinky do té omáčky?", profession: "kuchař" },
  { sentence: "Ich muss das Gemüse noch putzen und ___.", answer: "schneiden", translation: "Musím ještě očistit a nakrájet zeleninu.", profession: "kuchař" },
  { sentence: "Haben wir noch genug Vorräte im ___?", answer: "Kühlraum", translation: "Máme ještě dost zásob v chladicím boxu?", profession: "kuchař" },
  { sentence: "Die Bestellung für Tisch Nummer fünf ist ___.", answer: "fertig", translation: "Objednávka pro stůl číslo pět je hotová.", profession: "kuchař" },
  { sentence: "Ist in diesem Gericht ___ enthalten?", answer: "Knoblauch", translation: "Je v tomto jídle obsažen česnek?", profession: "kuchař" },
  { sentence: "Ist in diesem Gericht Fleisch ___?", answer: "enthalten", translation: "Obsahuje toto jídlo maso?", profession: "kuchař" },
  // === ČÍŠNÍK ===
  { sentence: "Haben Sie schon ___?", answer: "bestellt", translation: "Máte už objednáno?", profession: "číšník" },
  { sentence: "Ein großes Bier und die ___ bitte.", answer: "Speisekarte", translation: "Jedno velké pivo a jídelní lístek, prosím.", profession: "číšník" },
  { sentence: "Hat es Ihnen ___?", answer: "geschmeckt", translation: "Chutnalo vám?", profession: "číšník" },
  { sentence: "Ich bringe Ihnen sofort die ___.", answer: "Rechnung", translation: "Hned vám přinesu účet.", profession: "číšník" },
  { sentence: "Der Tisch am Fenster ist ___.", answer: "reserviert", translation: "Stůl u okna je rezervovaný.", profession: "číšník" },
  { sentence: "Möchten Sie zusammen oder getrennt ___?", answer: "bezahlen", translation: "Chcete platit dohromady, nebo zvlášť?", profession: "číšník" },
  { sentence: "Ich ___ Ihnen das Tagesmenü.", answer: "empfehle", translation: "Doporučuji vám denní menu.", profession: "číšník" },
  { sentence: "Möchten Sie schon einen Nachtisch ___?", answer: "bestellen", translation: "Chcete si už objednat dezert?", profession: "číšník" },
  { sentence: "Ich ___ den Tisch für vier Personen.", answer: "decke", translation: "Prostírám stůl pro čtyři osoby.", profession: "číšník" },
  { sentence: "Bringen Sie dem Gast bitte ein neues ___.", answer: "Besteck", translation: "Přineste prosím hostovi nový příbor.", profession: "číšník" },
  { sentence: "Die Gläser müssen ___ werden.", answer: "poliert", translation: "Ty sklenice se musí vyleštit.", profession: "číšník" },
  { sentence: "Wir haben heute eine Empfehlung vom ___.", answer: "Küchenchef", translation: "Dnes máme doporučení od šéfkuchaře.", profession: "číšník" },
  { sentence: "Ich nehme die ___ auf.", answer: "Getränkebestellung", translation: "Přijmu objednávku na nápoje.", profession: "číšník" },
  // === POKLADNÍ ===
  { sentence: "Guten Tag, haben Sie eine ___?", answer: "Kundenkarte", translation: "Dobrý den, máte zákaznickou kartu?", profession: "pokladní" },
  { sentence: "Das macht zusammen ___ Euro.", answer: "achtundzwanzig", translation: "Dělí to dohromady dvacet osm euro.", profession: "pokladní" },
  { sentence: "___ Sie bar oder mit Karte?", answer: "Zahlen", translation: "Platíte hotově, nebo kartou?", profession: "pokladní" },
  { sentence: "Brauchen Sie den ___?", answer: "Kassenbon", translation: "Potřebujete účtenku?", profession: "pokladní" },
  { sentence: "Obst und Gemüse müssen Sie dort ___.", answer: "abwiegen", translation: "Ovoce a zeleninu musíte zvážit tamto.", profession: "pokladní" },
  { sentence: "Können Sie bitte eine zweite Kasse ___?", answer: "öffnen", translation: "Můžete prosím otevřít druhou pokladnu?", profession: "pokladní" },
  { sentence: "Dieses Produkt ist leider ___.", answer: "ausverkauft", translation: "Tento produkt je bohužel vyprodaný.", profession: "pokladní" },
  { sentence: "Das Mindesthaltbarkeitsdatum ist ___.", answer: "abgelaufen", translation: "Datum minimální trvanlivosti vypršelo.", profession: "pokladní" },
  { sentence: "Vorsicht, der Boden ist frisch ___.", answer: "gewischt", translation: "Pozor, podlaha je čerstvě vytřená.", profession: "pokladní" },
  { sentence: "Wir müssen die Regale neu ___.", answer: "auffüllen", translation: "Musíme znovu doplnit regály.", profession: "pokladní" },
  { sentence: "Suchen Sie ein bestimmtes ___?", answer: "Produkt", translation: "Hledáte nějaký konkrétní produkt?", profession: "pokladní" },
  { sentence: "Die Pfandflaschen können Sie dort ___.", answer: "abgeben", translation: "Zálohované láhve můžete odevzdat tamto.", profession: "pokladní" },
  { sentence: "Haben Sie noch ___?", answer: "Kleingeld", translation: "Máte ještě drobné?", profession: "pokladní" },
  { sentence: "Das Angebot ___ nur bis Samstag.", answer: "gilt", translation: "Tato nabídka platí jen do soboty.", profession: "pokladní" },
  { sentence: "Entschuldigung, wo finde ich das ___?", answer: "Waschmittel", translation: "Omlouvám se, kde najdu prací prášek?", profession: "pokladní" },
  // === UKLÍZEČKA ===
  { sentence: "Ich fange heute im ersten ___ an.", answer: "Stock", translation: "Dnes začnu v prvním patře.", profession: "uklízečka" },
  { sentence: "Der Müll muss jeden Abend ___ werden.", answer: "geleert", translation: "Odpadky se musí vynášet každý večer.", profession: "uklízečka" },
  { sentence: "Wo stehen der ___ und der Wischer?", answer: "Staubsauger", translation: "Kde stojí vysavač a mop?", profession: "uklízečka" },
  { sentence: "Der Boden ist nass, bitte seien Sie ___.", answer: "vorsichtig", translation: "Podlaha je mokrá, buďte prosím opatrní.", profession: "uklízečka" },
  { sentence: "Ich habe alle Fenster im ___ geputzt.", answer: "Büro", translation: "Umyl(a) jsem všechna okna v kanceláři.", profession: "uklízečka" },
  { sentence: "Die ___ sind fast leer.", answer: "Reinigungsmittel", translation: "Čisticí prostředky jsou skoro pryč (spotřebované).", profession: "uklízečka" },
  { sentence: "Können Sie mir bitte neue ___ geben?", answer: "Lappen", translation: "Můžete mi prosím dát nové hadry?", profession: "uklízečka" },
  { sentence: "Muss ich heute auch den ___ reinigen?", answer: "Teppich", translation: "Musím dnes vyčistit i ten koberec?", profession: "uklízečka" },
  { sentence: "Bitte benutzen Sie diesen ___ für das Bad.", answer: "Reiniger", translation: "Prosím, použijte tento čistič na koupelnu.", profession: "uklízečka" },
  { sentence: "Ich bin fertig mit dem ___.", answer: "Treppenhaus", translation: "Jsem hotov(a) se schodištěm.", profession: "uklízečka" },
  { sentence: "Gibt es einen Schlüssel für diesen ___?", answer: "Raum", translation: "Existuje od této místnosti klíč?", profession: "uklízečka" },
  { sentence: "Ich habe den ___ auf den Regalen gewischt.", answer: "Staub", translation: "Utřel(a) jsem prach na regálech.", profession: "uklízečka" },
  { sentence: "Das ___ ist leider verstopft.", answer: "Waschbecken", translation: "Umyvadlo je bohužel ucpané.", profession: "uklízečka" },
  { sentence: "Wir brauchen mehr ___ und Toilettenpapier.", answer: "Seife", translation: "Potřebujeme víc mýdla a toaletního papíru.", profession: "uklízečka" },
   { sentence: "Haben Sie noch spezielle ___ für heute?", answer: "Wünsche", translation: "Máte pro dnešek ještě nějaká speciální přání?", profession: "uklízečka" },
   // === AUTOMECHANIK ===
   { sentence: "Ich muss das ___ wechseln.", answer: "Öl", translation: "Musím vyměnit olej.", profession: "automechanik" },
   { sentence: "Die Batterie ist ___.", answer: "leer", translation: "Baterie je vybitá.", profession: "automechanik" },
   { sentence: "Können Sie den ___ prüfen?", answer: "Reifendruck", translation: "Můžete zkontrolovat tlak v pneumatikách?", profession: "automechanik" },
];

// Helper to extract German word from question text
function extractGermanWord(q: Question): string {
  const match = q.text.match(/má\s+(.+)\?/);
  return match ? match[1] : "";
}

// Helper to get article for a question
function getArticle(q: Question): string {
  return q.options[q.correct];
}

export interface FlashCard {
  german: string;
  czech: string;
  type: "noun" | "sentence";
  profession: Profession;
}

export function getAllFlashCards(): FlashCard[] {
  const nounCards: FlashCard[] = QUESTIONS.map((q) => ({
    german: `${getArticle(q)} ${extractGermanWord(q)}`,
    czech: q.translation,
    type: "noun" as const,
    profession: q.profession,
  }));

  const sentenceCards: FlashCard[] = FILL_QUESTIONS.map((q) => ({
    german: q.sentence.replace("___", q.answer),
    czech: q.translation,
    type: "sentence" as const,
    profession: q.profession,
  }));

  return [...nounCards, ...sentenceCards];
}

/** Filter questions by selected professions. Strict: only matching professions are returned. */
export function filterByProfession<T extends { profession: Profession }>(
  items: T[],
  selectedProfessions: Profession[]
): T[] {
  if (selectedProfessions.length === 0) return items;
  return items.filter(
    (item) => selectedProfessions.includes(item.profession)
  );
}
