export interface Question {
  text: string;
  options: string[];
  correct: number;
  translation: string;
}

export interface FillQuestion {
  sentence: string;
  answer: string;
  translation: string;
}

export const QUESTIONS: Question[] = [
  { text: "Jaký člen má Lama?", options: ["der", "die", "das"], correct: 2, translation: "lama" },
  { text: "Jaký člen má Haus?", options: ["der", "die", "das"], correct: 2, translation: "dům" },
  { text: "Jaký člen má Hund?", options: ["der", "die", "das"], correct: 0, translation: "pes" },
  { text: "Jaký člen má Katze?", options: ["der", "die", "das"], correct: 1, translation: "kočka" },
  { text: "Jaký člen má Buch?", options: ["der", "die", "das"], correct: 2, translation: "kniha" },
  { text: "Jaký člen má Tisch?", options: ["der", "die", "das"], correct: 0, translation: "stůl" },
  { text: "Jaký člen má Blume?", options: ["der", "die", "das"], correct: 1, translation: "květina" },
  { text: "Jaký člen má Auto?", options: ["der", "die", "das"], correct: 2, translation: "auto" },
  { text: "Jaký člen má Baum?", options: ["der", "die", "das"], correct: 0, translation: "strom" },
  { text: "Jaký člen má Schule?", options: ["der", "die", "das"], correct: 1, translation: "škola" },
  { text: "Jaký člen má Schreibtisch?", options: ["der", "die", "das"], correct: 0, translation: "psací stůl" },
  { text: "Jaký člen má Stuhl?", options: ["der", "die", "das"], correct: 0, translation: "židle" },
  { text: "Jaký člen má Computer?", options: ["der", "die", "das"], correct: 0, translation: "počítač" },
  { text: "Jaký člen má Monitor?", options: ["der", "die", "das"], correct: 0, translation: "monitor" },
  { text: "Jaký člen má Tastatur?", options: ["der", "die", "das"], correct: 1, translation: "klávesnice" },
  { text: "Jaký člen má Maus?", options: ["der", "die", "das"], correct: 1, translation: "myš" },
  { text: "Jaký člen má Dokument?", options: ["der", "die", "das"], correct: 2, translation: "dokument" },
  { text: "Jaký člen má Formular?", options: ["der", "die", "das"], correct: 2, translation: "formulář" },
  { text: "Jaký člen má Büro?", options: ["der", "die", "das"], correct: 2, translation: "kancelář" },
  { text: "Jaký člen má Drucker?", options: ["der", "die", "das"], correct: 0, translation: "tiskárna" },
  { text: "Jaký člen má Scanner?", options: ["der", "die", "das"], correct: 0, translation: "skener" },
  { text: "Jaký člen má Kopierer?", options: ["der", "die", "das"], correct: 0, translation: "kopírka" },
  { text: "Jaký člen má Aktenschrank?", options: ["der", "die", "das"], correct: 0, translation: "kartotéka" },
  { text: "Jaký člen má Regal?", options: ["der", "die", "das"], correct: 2, translation: "regál" },
  { text: "Jaký člen má Telefon?", options: ["der", "die", "das"], correct: 2, translation: "telefon" },
  { text: "Jaký člen má E-Mail?", options: ["der", "die", "das"], correct: 1, translation: "e-mail" },
  { text: "Jaký člen má Besprechung?", options: ["der", "die", "das"], correct: 1, translation: "porada" },
  { text: "Jaký člen má Pause?", options: ["der", "die", "das"], correct: 1, translation: "přestávka" },
  { text: "Jaký člen má Kantine?", options: ["der", "die", "das"], correct: 1, translation: "jídelna" },
  { text: "Jaký člen má Notebook?", options: ["der", "die", "das"], correct: 2, translation: "notebook" },
  { text: "Jaký člen má Schrank?", options: ["der", "die", "das"], correct: 0, translation: "skříň" },
  { text: "Jaký člen má Tür?", options: ["der", "die", "das"], correct: 1, translation: "dveře" },
  { text: "Jaký člen má Fenster?", options: ["der", "die", "das"], correct: 2, translation: "okno" },
  { text: "Jaký člen má Papierkorb?", options: ["der", "die", "das"], correct: 0, translation: "koš" },
  { text: "Jaký člen má Lampe?", options: ["der", "die", "das"], correct: 1, translation: "lampa" },
  { text: "Jaký člen má Whiteboard?", options: ["der", "die", "das"], correct: 2, translation: "tabule" },
  { text: "Jaký člen má Chef?", options: ["der", "die", "das"], correct: 0, translation: "šéf" },
  { text: "Jaký člen má Kollegin?", options: ["der", "die", "das"], correct: 1, translation: "kolegyně" },
  { text: "Jaký člen má Kollege?", options: ["der", "die", "das"], correct: 0, translation: "kolega" },
  { text: "Jaký člen má Meeting?", options: ["der", "die", "das"], correct: 2, translation: "schůzka" },
  { text: "Jaký člen má Projektor?", options: ["der", "die", "das"], correct: 0, translation: "projektor" },
  { text: "Jaký člen má Präsentation?", options: ["der", "die", "das"], correct: 1, translation: "prezentace" },
  { text: "Jaký člen má WC?", options: ["der", "die", "das"], correct: 2, translation: "záchod" },
  { text: "Jaký člen má Umkleide?", options: ["der", "die", "das"], correct: 1, translation: "šatna" },
  { text: "Jaký člen má Schicht?", options: ["der", "die", "das"], correct: 1, translation: "směna" },
  { text: "Jaký člen má Frühschicht?", options: ["der", "die", "das"], correct: 1, translation: "ranní směna" },
  { text: "Jaký člen má Spätschicht?", options: ["der", "die", "das"], correct: 1, translation: "odpolední směna" },
  { text: "Jaký člen má Nachtschicht?", options: ["der", "die", "das"], correct: 1, translation: "noční směna" },
  { text: "Jaký člen má Tagschicht?", options: ["der", "die", "das"], correct: 1, translation: "denní směna" },
  { text: "Jaký člen má Schichtplan?", options: ["der", "die", "das"], correct: 0, translation: "plán směn" },
  { text: "Jaký člen má Arbeitszeit?", options: ["der", "die", "das"], correct: 1, translation: "pracovní doba" },
  { text: "Jaký člen má Teilzeit?", options: ["der", "die", "das"], correct: 1, translation: "zkrácený úvazek" },
  { text: "Jaký člen má Vollzeit?", options: ["der", "die", "das"], correct: 1, translation: "plný úvazek" },
  { text: "Jaký člen má Gleitzeit?", options: ["der", "die", "das"], correct: 1, translation: "pružná pracovní doba" },
  { text: "Jaký člen má Dienstplan?", options: ["der", "die", "das"], correct: 0, translation: "rozpis služeb" },
  { text: "Jaký člen má Urlaub?", options: ["der", "die", "das"], correct: 0, translation: "dovolená" },
  { text: "Jaký člen má Feiertag?", options: ["der", "die", "das"], correct: 0, translation: "svátek" },
  { text: "Jaký člen má Krankmeldung?", options: ["der", "die", "das"], correct: 1, translation: "nahlášení nemoci" },
  { text: "Jaký člen má Vertretung?", options: ["der", "die", "das"], correct: 1, translation: "zástup" },
  { text: "Jaký člen má Spind?", options: ["der", "die", "das"], correct: 0, translation: "skříňka" },
  { text: "Jaký člen má Seife?", options: ["der", "die", "das"], correct: 1, translation: "mýdlo" },
  { text: "Jaký člen má Erste Hilfe?", options: ["der", "die", "das"], correct: 1, translation: "první pomoc" },
  { text: "Jaký člen má Feuerlöscher?", options: ["der", "die", "das"], correct: 0, translation: "hasicí přístroj" },
  { text: "Jaký člen má Unfall?", options: ["der", "die", "das"], correct: 0, translation: "úraz" },
  { text: "Jaký člen má Warnweste?", options: ["der", "die", "das"], correct: 1, translation: "výstražná vesta" },
  { text: "Jaký člen má Helm?", options: ["der", "die", "das"], correct: 0, translation: "helma" },
  { text: "Jaký člen má Schutzbrille?", options: ["der", "die", "das"], correct: 1, translation: "ochranné brýle" },
  { text: "Jaký člen má Vorschrift?", options: ["der", "die", "das"], correct: 1, translation: "předpis" },
  { text: "Jaký člen má Sicherheit?", options: ["der", "die", "das"], correct: 1, translation: "bezpečnost" },
  { text: "Jaký člen má Fließband?", options: ["der", "die", "das"], correct: 2, translation: "výrobní pás" },
  { text: "Jaký člen má Reparatur?", options: ["der", "die", "das"], correct: 1, translation: "oprava" },
  { text: "Jaký člen má Störung?", options: ["der", "die", "das"], correct: 1, translation: "porucha" },
  { text: "Jaký člen má Defekt?", options: ["der", "die", "das"], correct: 0, translation: "závada" },
  { text: "Jaký člen má Schraube?", options: ["der", "die", "das"], correct: 1, translation: "šroub" },
  { text: "Jaký člen má Bohrmaschine?", options: ["der", "die", "das"], correct: 1, translation: "vrtačka" },
  { text: "Jaký člen má Qualität?", options: ["der", "die", "das"], correct: 1, translation: "kvalita" },
  { text: "Jaký člen má Material?", options: ["der", "die", "das"], correct: 2, translation: "materiál" },
  { text: "Jaký člen má Sicherheitsschuhe?", options: ["der", "die", "das"], correct: 1, translation: "bezpečnostní boty" },
  { text: "Jaký člen má Brett?", options: ["der", "die", "das"], correct: 2, translation: "deska / prkno" },
  { text: "Jaký člen má Eichenholz?", options: ["der", "die", "das"], correct: 2, translation: "dubové dřevo" },
  { text: "Jaký člen má Gerüst?", options: ["der", "die", "das"], correct: 2, translation: "lešení" },
  { text: "Jaký člen má Zement?", options: ["der", "die", "das"], correct: 0, translation: "cement" },
  { text: "Jaký člen má Pläne?", options: ["der", "die", "das"], correct: 1, translation: "plány" },
  { text: "Jaký člen má Erdgeschoss?", options: ["der", "die", "das"], correct: 2, translation: "přízemí" },
  { text: "Jaký člen má Patient?", options: ["der", "die", "das"], correct: 0, translation: "pacient" },
  { text: "Jaký člen má Fieber?", options: ["der", "die", "das"], correct: 2, translation: "teplota / horečka" },
  { text: "Jaký člen má Medikamente?", options: ["der", "die", "das"], correct: 1, translation: "léky" },
  { text: "Jaký člen má Tagesmenü?", options: ["der", "die", "das"], correct: 2, translation: "denní menu" },
  { text: "Jaký člen má Gericht?", options: ["der", "die", "das"], correct: 2, translation: "jídlo / pokrm" },
  { text: "Jaký člen má Fleisch?", options: ["der", "die", "das"], correct: 2, translation: "maso" },
  { text: "Jaký člen má Werkstatt?", options: ["der", "die", "das"], correct: 1, translation: "dílna" },
  { text: "Jaký člen má Hammer?", options: ["der", "die", "das"], correct: 0, translation: "kladivo" },
  { text: "Jaký člen má Moment?", options: ["der", "die", "das"], correct: 0, translation: "moment / chvilka" },
  { text: "Jaký člen má Zeit?", options: ["der", "die", "das"], correct: 1, translation: "čas" },
  { text: "Jaký člen má Maschine?", options: ["der", "die", "das"], correct: 1, translation: "stroj" },
  { text: "Jaký člen má Teil?", options: ["der", "die", "das"], correct: 2, translation: "díl / součástka" },
  { text: "Jaký člen má Förderband?", options: ["der", "die", "das"], correct: 2, translation: "dopravní pás" },
  { text: "Jaký člen má Quote?", options: ["der", "die", "das"], correct: 1, translation: "kvóta" },
  { text: "Jaký člen má Stunde?", options: ["der", "die", "das"], correct: 1, translation: "hodina" },
  { text: "Jaký člen má Holz?", options: ["der", "die", "das"], correct: 2, translation: "dřevo" },
  { text: "Jaký člen má Verarbeitung?", options: ["der", "die", "das"], correct: 1, translation: "zpracování" },
  { text: "Jaký člen má Kanten?", options: ["der", "die", "das"], correct: 1, translation: "hrany" },
  { text: "Jaký člen má Säge?", options: ["der", "die", "das"], correct: 1, translation: "pila" },
  { text: "Jaký člen má Leim?", options: ["der", "die", "das"], correct: 0, translation: "lepidlo" },
  { text: "Jaký člen má Mörtel?", options: ["der", "die", "das"], correct: 0, translation: "malta" },
  { text: "Jaký člen má Mauer?", options: ["der", "die", "das"], correct: 1, translation: "zeď" },
  { text: "Jaký člen má Baustelle?", options: ["der", "die", "das"], correct: 1, translation: "stavba (místo)" },
  { text: "Jaký člen má Blut?", options: ["der", "die", "das"], correct: 2, translation: "krev" },
  { text: "Jaký člen má Schmerzen?", options: ["der", "die", "das"], correct: 1, translation: "bolesti" },
  { text: "Jaký člen má Schwindel?", options: ["der", "die", "das"], correct: 0, translation: "závrať" },
  { text: "Jaký člen má Arzt?", options: ["der", "die", "das"], correct: 0, translation: "lékař" },
  { text: "Jaký člen má Visite?", options: ["der", "die", "das"], correct: 1, translation: "vizita" },
  { text: "Jaký člen má Bier?", options: ["der", "die", "das"], correct: 2, translation: "pivo" },
  { text: "Jaký člen má Speisekarte?", options: ["der", "die", "das"], correct: 1, translation: "jídelní lístek" },
  { text: "Jaký člen má Rechnung?", options: ["der", "die", "das"], correct: 1, translation: "účet / faktura" },
  { text: "Jaký člen má Schichtbetrieb?", options: ["der", "die", "das"], correct: 0, translation: "směnný provoz" },
  { text: "Jaký člen má Schutzkleidung?", options: ["der", "die", "das"], correct: 1, translation: "ochranný oděv" },
  { text: "Jaký člen má Werkzeuge?", options: ["der", "die", "das"], correct: 1, translation: "nářadí" },
  { text: "Jaký člen má Einladung?", options: ["der", "die", "das"], correct: 1, translation: "pozvánka" },
  { text: "Jaký člen má Termin?", options: ["der", "die", "das"], correct: 0, translation: "termín" },
  { text: "Jaký člen má Homeoffice?", options: ["der", "die", "das"], correct: 2, translation: "home office" },
  { text: "Jaký člen má Entscheidung?", options: ["der", "die", "das"], correct: 1, translation: "rozhodnutí" },
  { text: "Jaký člen má Projekt?", options: ["der", "die", "das"], correct: 2, translation: "projekt" },
  { text: "Jaký člen má Priorität?", options: ["der", "die", "das"], correct: 1, translation: "priorita" },
  { text: "Jaký člen má Feedback?", options: ["der", "die", "das"], correct: 2, translation: "zpětná vazba" },
  { text: "Jaký člen má Entwurf?", options: ["der", "die", "das"], correct: 0, translation: "návrh" },
  { text: "Jaký člen má Status?", options: ["der", "die", "das"], correct: 0, translation: "stav" },
  { text: "Jaký člen má Kosten?", options: ["der", "die", "das"], correct: 1, translation: "náklady" },
  { text: "Jaký člen má Team?", options: ["der", "die", "das"], correct: 2, translation: "tým" },
  { text: "Jaký člen má Unterlagen?", options: ["der", "die", "das"], correct: 1, translation: "podklady" },
  { text: "Jaký člen má Deadline?", options: ["der", "die", "das"], correct: 1, translation: "termín (uzávěrka)" },
  { text: "Jaký člen má Zusammenarbeit?", options: ["der", "die", "das"], correct: 1, translation: "spolupráce" },
  { text: "Jaký člen má Messer?", options: ["der", "die", "das"], correct: 2, translation: "nůž" },
  { text: "Jaký člen má Pfanne?", options: ["der", "die", "das"], correct: 1, translation: "pánev" },
  { text: "Jaký člen má Kochtopf?", options: ["der", "die", "das"], correct: 0, translation: "hrnec" },
  { text: "Jaký člen má Suppe?", options: ["der", "die", "das"], correct: 1, translation: "polévka" },
  { text: "Jaký člen má Teller?", options: ["der", "die", "das"], correct: 0, translation: "talíř" },
  { text: "Jaký člen má Kräuter?", options: ["der", "die", "das"], correct: 1, translation: "bylinky" },
  { text: "Jaký člen má Soße?", options: ["der", "die", "das"], correct: 1, translation: "omáčka" },
  { text: "Jaký člen má Gemüse?", options: ["der", "die", "das"], correct: 2, translation: "zelenina" },
  { text: "Jaký člen má Kühlraum?", options: ["der", "die", "das"], correct: 0, translation: "chladicí místnost / box" },
  { text: "Jaký člen má Nachtisch?", options: ["der", "die", "das"], correct: 0, translation: "dezert" },
  { text: "Jaký člen má Besteck?", options: ["der", "die", "das"], correct: 2, translation: "příbor" },
  { text: "Jaký člen má Glas?", options: ["der", "die", "das"], correct: 2, translation: "sklenice" },
  { text: "Jaký člen má Knoblauch?", options: ["der", "die", "das"], correct: 0, translation: "česnek" },
  { text: "Jaký člen má Küchenchef?", options: ["der", "die", "das"], correct: 0, translation: "šéfkuchař" },
  { text: "Jaký člen má Serviette?", options: ["der", "die", "das"], correct: 1, translation: "ubrousek" },
  { text: "Jaký člen má Tischdecke?", options: ["der", "die", "das"], correct: 1, translation: "ubrus" },
  { text: "Jaký člen má Trinkgeld?", options: ["der", "die", "das"], correct: 2, translation: "spropitné" },
  { text: "Jaký člen má Allergie?", options: ["der", "die", "das"], correct: 1, translation: "alergie" },
  { text: "Jaký člen má Vorspeise?", options: ["der", "die", "das"], correct: 1, translation: "předkrm" },
  { text: "Jaký člen má Hauptgericht?", options: ["der", "die", "das"], correct: 2, translation: "hlavní chod" },
];

export const FILL_QUESTIONS: FillQuestion[] = [
  { sentence: "Ich ___ Deutsch.", answer: "spreche", translation: "Já mluvím německy." },
  { sentence: "Er ___ ein Buch.", answer: "liest", translation: "On čte knihu." },
  { sentence: "Wir ___ nach Hause.", answer: "gehen", translation: "My jdeme domů." },
  { sentence: "Sie ___ Kaffee.", answer: "trinkt", translation: "Ona pije kávu." },
  { sentence: "Du ___ sehr schnell.", answer: "läufst", translation: "Ty běžíš velmi rychle." },
  { sentence: "Ich ___ müde.", answer: "bin", translation: "Já jsem unavený/á." },
  { sentence: "Er ___ Lehrer.", answer: "ist", translation: "On je učitel." },
  { sentence: "Wir ___ Studenten.", answer: "sind", translation: "My jsme studenti." },
  { sentence: "Sie ___ eine Katze.", answer: "hat", translation: "Ona má kočku." },
  { sentence: "Du ___ Hunger.", answer: "hast", translation: "Ty máš hlad." },
  { sentence: "Ich ___ gern Musik.", answer: "höre", translation: "Já rád/a poslouchám hudbu." },
  { sentence: "Er ___ Fußball.", answer: "spielt", translation: "On hraje fotbal." },
  { sentence: "Wir ___ ins Kino.", answer: "gehen", translation: "My jdeme do kina." },
  { sentence: "Sie ___ sehr gut.", answer: "kocht", translation: "Ona vaří velmi dobře." },
  { sentence: "Du ___ schön.", answer: "singst", translation: "Ty zpíváš krásně." },
  { sentence: "Ich ___ Wasser.", answer: "trinke", translation: "Já piji vodu." },
  { sentence: "Er ___ die Tür.", answer: "öffnet", translation: "On otevírá dveře." },
  { sentence: "Wir ___ Deutsch.", answer: "lernen", translation: "My se učíme německy." },
  { sentence: "Sie ___ das Fenster.", answer: "schließt", translation: "Ona zavírá okno." },
  { sentence: "Du ___ mir.", answer: "hilfst", translation: "Ty mi pomáháš." },
  { sentence: "Wann ___ du an zu arbeiten?", answer: "fängst", translation: "Kdy začínáš pracovat?" },
  { sentence: "Hast du heute viel ___?", answer: "Arbeit", translation: "Máš dnes hodně práce?" },
  { sentence: "Kannst du mir damit ___?", answer: "helfen", translation: "Můžeš mi s tím pomoct?" },
  { sentence: "Wer ist dafür ___?", answer: "verantwortlich", translation: "Kdo je za to zodpovědný?" },
  { sentence: "Ich ___ mehr Zeit.", answer: "brauche", translation: "Potřebuji více času." },
  { sentence: "Das ist nicht meine ___.", answer: "Verantwortung", translation: "To není moje zodpovědnost." },
  { sentence: "Ich habe einen Fehler ___.", answer: "gemacht", translation: "Udělal jsem chybu." },
  { sentence: "Wo sind die ___?", answer: "Schutzhandschuhe", translation: "Kde jsou ochranné rukavice?" },
  { sentence: "Muss ich eine Schutzbrille ___?", answer: "tragen", translation: "Musím nosit ochranné brýle?" },
  { sentence: "Das ist ___.", answer: "gefährlich", translation: "To je nebezpečné." },
  { sentence: "___ auf!", answer: "Pass", translation: "Dávej pozor!" },
  { sentence: "Die Maschine ist ___.", answer: "kaputt", translation: "Ten stroj je rozbitý." },
  { sentence: "Wer ist für die Sicherheit ___?", answer: "verantwortlich", translation: "Kdo je zodpovědný za bezpečnost?" },
  { sentence: "Wir sollten das ___.", answer: "melden", translation: "Měli bychom to nahlásit." },
  { sentence: "Ich brauche eine ___.", answer: "Sicherheitsschulung", translation: "Potřebuji bezpečnostní školení." },
  { sentence: "Kannst du die Maschine ___?", answer: "ausschalten", translation: "Můžeš vypnout ten stroj?" },
  { sentence: "Kannst du mir das ___?", answer: "erklären", translation: "Můžeš mi to vysvětlit?" },
  { sentence: "Ich bin nicht deiner ___.", answer: "Meinung", translation: "Nesouhlasím s tebou." },
  { sentence: "Das ist keine gute ___.", answer: "Idee", translation: "To není dobrý nápad." },
  { sentence: "Hast du heute ___?", answer: "Zeit", translation: "Máš dnes čas?" },
  { sentence: "Machen wir das ___?", answer: "zusammen", translation: "Uděláme to společně?" },
  { sentence: "Das ist nicht ___.", answer: "fair", translation: "To není fér." },
  { sentence: "Das ist nicht mein ___.", answer: "Problem", translation: "To není můj problém." },
  { sentence: "Können wir eine Lösung ___?", answer: "finden", translation: "Můžeme najít řešení?" },
  { sentence: "Warum hast du das ___?", answer: "gemacht", translation: "Proč jsi to udělal?" },
  { sentence: "Das war ein ___.", answer: "Missverständnis", translation: "To bylo nedorozumění." },
  { sentence: "Ich habe eine ___.", answer: "Frage", translation: "Mám otázku." },
  { sentence: "Ich brauche ___.", answer: "Urlaub", translation: "Potřebuji dovolenou." },
  { sentence: "Mein Kind ist ___.", answer: "krank", translation: "Moje dítě je nemocné." },
  { sentence: "Ich bin damit nicht ___.", answer: "zufrieden", translation: "Nejsem s tím spokojený." },
  { sentence: "Ich entschuldige mich für den ___.", answer: "Fehler", translation: "Omlouvám se za chybu." },
  { sentence: "Ich ___ dir die Einladung zum Meeting.", answer: "schicke", translation: "Posílám ti pozvánku na schůzku." },
  { sentence: "Können wir den Termin ___?", answer: "verschieben", translation: "Můžeme ten termín posunout?" },
  { sentence: "Ich bin heute im ___.", answer: "Homeoffice", translation: "Dnes jsem na home office." },
  { sentence: "Haben wir dazu schon eine ___?", answer: "Entscheidung", translation: "Máme k tomu už nějaké rozhodnutí?" },
  { sentence: "Ich ___ mich darum.", answer: "kümmere", translation: "Postarám se o to." },
  { sentence: "Das Projekt hat hohe ___.", answer: "Priorität", translation: "Tento projekt má vysokou prioritu." },
  { sentence: "___ mir bitte eine kurze E-Mail.", answer: "Schreib", translation: "Napiš mi prosím krátký e-mail." },
  { sentence: "Ich brauche dein ___ zu diesem Entwurf.", answer: "Feedback", translation: "Potřebuji tvoji zpětnou vazbu k tomuto návrhu." },
  { sentence: "Wie ist der aktuelle ___?", answer: "Status", translation: "Jaký je aktuální stav?" },
  { sentence: "Wir müssen die Kosten ___.", answer: "senken", translation: "Musíme snížit náklady." },
  { sentence: "Ich habe eine Frage zur ___.", answer: "Rechnung", translation: "Mám dotaz k faktuře." },
  { sentence: "Unser Team arbeitet sehr ___.", answer: "effizient", translation: "Náš tým pracuje velmi efektivně." },
  { sentence: "Kannst du mir die Unterlagen ___?", answer: "schicken", translation: "Můžeš mi poslat ty podklady?" },
  { sentence: "Wir ___ das beim nächsten Mal.", answer: "besprechen", translation: "Probereme to příště." },
  { sentence: "Ich bin gleich ___.", answer: "fertig", translation: "Budu hned hotov." },
  { sentence: "Die Deadline ist morgen ___.", answer: "Mittag", translation: "Termín (deadline) je zítra v poledne." },
  { sentence: "Das ist ein technisches ___.", answer: "Problem", translation: "To je technický problém." },
  { sentence: "Ich ___ mich später bei Ihnen.", answer: "melde", translation: "Ozvu se Vám později." },
  { sentence: "Vielen Dank für die gute ___.", answer: "Zusammenarbeit", translation: "Děkuji moc za dobrou spolupráci." },
  { sentence: "Wo ___ ich das Dokument?", answer: "finde", translation: "Kde najdu ten dokument?" },
  { sentence: "Die Maschine muss sofort ___ werden.", answer: "gestoppt", translation: "Ten stroj se musí okamžitě zastavit." },
  { sentence: "___ das Teil auf das Förderband.", answer: "Leg", translation: "Polož ten díl na dopravní pás." },
  { sentence: "Wir müssen die ___ pro Stunde einhalten.", answer: "Quote", translation: "Musíme dodržet kvótu za hodinu." },
  { sentence: "Dieses Holz ist zu ___ für die Verarbeitung.", answer: "feucht", translation: "Toto dřevo je příliš vlhké na zpracování." },
  { sentence: "Ich muss die Kanten noch ___.", answer: "schleifen", translation: "Musím ještě zbrousit hrany." },
  { sentence: "Wo ist die ___ und der Leim?", answer: "Säge", translation: "Kde je pila a lepidlo?" },
  { sentence: "___ bitte den Mörtel an.", answer: "Misch", translation: "Namíchej prosím maltu." },
  { sentence: "Die Mauer muss genau ___ sein.", answer: "gerade", translation: "Ta zeď musí být přesně rovná." },
  { sentence: "Tragen Sie auf der Baustelle immer einen ___.", answer: "Helm", translation: "Na stavbě noste vždy helmu." },
  { sentence: "Ich muss Ihnen Blut ___.", answer: "abnehmen", translation: "Musím vám odebrat krev." },
  { sentence: "Haben Sie Schmerzen oder ___?", answer: "Schwindel", translation: "Máte bolesti nebo závratě?" },
  { sentence: "Der Arzt kommt gleich zur ___.", answer: "Visite", translation: "Lékař přijde hned na vizitu." },
  { sentence: "Haben Sie schon ___?", answer: "bestellt", translation: "Máte už objednáno?" },
  { sentence: "Ein großes Bier und die ___ bitte.", answer: "Speisekarte", translation: "Jedno velké pivo a jídelní lístek, prosím." },
  { sentence: "Hat es Ihnen ___?", answer: "geschmeckt", translation: "Chutnalo vám?" },
  { sentence: "Ich bringe Ihnen sofort die ___.", answer: "Rechnung", translation: "Hned vám přinesu účet." },
  { sentence: "Wir arbeiten im ___.", answer: "Schichtbetrieb", translation: "Pracujeme na směny." },
  { sentence: "Ist die Schutzkleidung ___?", answer: "obligatorisch", translation: "Je ochranný oděv povinný?" },
  { sentence: "Die Werkzeuge müssen ___ werden.", answer: "gereinigt", translation: "Nářadí se musí vyčistit." },
  { sentence: "Ich brauche eine kurze ___.", answer: "Pause", translation: "Potřebuji krátkou pauzu." },
  { sentence: "___ Sie bitte die Qualität der Teile.", answer: "Kontrollieren", translation: "Zkontrolujte prosím kvalitu těch dílů." },
  { sentence: "Das Material ist fast leer, wir müssen neues ___.", answer: "bestellen", translation: "Materiál skoro došel, musíme objednat nový." },
  { sentence: "Haben Sie die Sicherheitsschuhe ___?", answer: "angezogen", translation: "Máte obuté bezpečnostní boty?" },
  { sentence: "Ich habe das Brett falsch ___.", answer: "zugeschnitten", translation: "Špatně jsem tu desku uřízl." },
  { sentence: "Der Schrank ist aus massivem ___.", answer: "Eichenholz", translation: "Ta skříň je z masivního dubového dřeva." },
  { sentence: "Können Sie mir beim Tragen ___?", answer: "helfen", translation: "Můžete mi pomoci s nošením?" },
  { sentence: "Wir bauen heute das ___ auf.", answer: "Gerüst", translation: "Dnes stavíme lešení." },
  { sentence: "Der Zement muss noch zwei Stunden ___.", answer: "trocknen", translation: "Cement musí ještě dvě hodiny schnout." },
  { sentence: "Wo sind die Pläne für das ___?", answer: "Erdgeschoss", translation: "Kde jsou plány pro přízemí?" },
  { sentence: "Ich muss bei diesem Patienten Fieber ___.", answer: "messen", translation: "Musím tomuto pacientovi změřit teplotu." },
  { sentence: "Haben Sie Ihre Medikamente schon ___?", answer: "genommen", translation: "Už jste si vzal své léky?" },
  { sentence: "Ich ___ Ihnen beim Aufstehen.", answer: "helfe", translation: "Pomůžu vám se vstáváním." },
  { sentence: "Der Tisch am Fenster ist ___.", answer: "reserviert", translation: "Stůl u okna je rezervovaný." },
  { sentence: "Möchten Sie zusammen oder getrennt ___?", answer: "bezahlen", translation: "Chcete platit dohromady, nebo zvlášť?" },
  { sentence: "Ich ___ Ihnen das Tagesmenü.", answer: "empfehle", translation: "Doporučuji vám denní menu." },
  { sentence: "Ist in diesem Gericht Fleisch ___?", answer: "enthalten", translation: "Obsahuje toto jídlo maso?" },
  { sentence: "Wer hat heute Abend die ___?", answer: "Nachtschicht", translation: "Kdo má dnes večer noční směnu?" },
  { sentence: "Wir müssen die Werkstatt sauber ___.", answer: "machen", translation: "Musíme uklidit dílnu." },
  { sentence: "___ Sie mir bitte den Hammer.", answer: "Geben", translation: "Dejte mi prosím to kladivo." },
  { sentence: "Haben Sie einen Moment ___ für mich?", answer: "Zeit", translation: "Máte na mě chvilku čas?" },
];

// Helper to extract German word from question text
function extractGermanWord(q: Question): string {
  const match = q.text.match(/má\s+(.+)\?/);
  return match ? match[1] : "";
}

// Helper to get article for a question
function getArticle(q: Question): string {
  return q.options[q.correct];
}

export interface FlashCard {
  german: string;
  czech: string;
  type: "noun" | "sentence";
}

export function getAllFlashCards(): FlashCard[] {
  const nounCards: FlashCard[] = QUESTIONS.map((q) => ({
    german: `${getArticle(q)} ${extractGermanWord(q)}`,
    czech: q.translation,
    type: "noun" as const,
  }));

  const sentenceCards: FlashCard[] = FILL_QUESTIONS.map((q) => ({
    german: q.sentence.replace("___", q.answer),
    czech: q.translation,
    type: "sentence" as const,
  }));

  return [...nounCards, ...sentenceCards];
}
