#!/usr/bin/env python3
"""Add translationUk to QUESTIONS entries in vocabularyData.ts"""
import re

Q_UK = {
    "llama": "лама",
    "house": "будинок",
    "dog": "собака",
    "cat": "кіт",
    "book": "книга",
    "table": "стіл",
    "flower": "квітка",
    "car": "автомобіль",
    "tree": "дерево",
    "school": "школа",
    "desk": "письмовий стіл",
    "chair": "стілець",
    "computer": "комп'ютер",
    "monitor": "монітор",
    "keyboard": "клавіатура",
    "mouse": "миша",
    "document": "документ",
    "form": "бланк",
    "office": "офіс",
    "printer": "принтер",
    "scanner": "сканер",
    "photocopier": "ксерокс",
    "filing cabinet": "картотека",
    "shelf": "полиця",
    "telephone": "телефон",
    "email": "електронна пошта",
    "meeting": "нарада",
    "laptop": "ноутбук",
    "waste bin": "кошик для паперу",
    "whiteboard": "дошка",
    "boss": "начальник",
    "colleague": "колега",
    "projector": "проектор",
    "presentation": "презентація",
    "invitation": "запрошення",
    "appointment": "зустріч/запис",
    "home office": "домашній офіс",
    "decision": "рішення",
    "project": "проект",
    "priority": "пріоритет",
    "feedback": "зворотний зв'язок",
    "draft": "чернетка",
    "status": "статус",
    "costs": "витрати",
    "team": "команда",
    "paperwork": "документи",
    "deadline": "дедлайн",
    "cooperation": "співпраця",
    "end of work": "кінець робочого дня",
    "break": "перерва",
    "canteen": "їдальня",
    "wardrobe": "шафа",
    "door": "двері",
    "window": "вікно",
    "lamp": "лампа",
    "toilet": "туалет",
    "changing room": "роздягальня",
    "shift": "зміна",
    "morning shift": "ранкова зміна",
    "late shift": "вечірня зміна",
    "night shift": "нічна зміна",
    "day shift": "денна зміна",
    "shift schedule": "графік змін",
    "working hours": "робочий час",
    "part-time": "неповний робочий день",
    "full-time": "повний робочий день",
    "flexitime": "гнучкий графік",
    "duty roster": "розклад чергувань",
    "holiday": "відпустка",
    "public holiday": "державне свято",
    "sick note": "лікарняний листок",
    "substitute": "заміна",
    "locker": "шафка",
    "first aid": "перша допомога",
    "fire extinguisher": "вогнегасник",
    "accident": "нещасний випадок",
    "high-vis vest": "жилет безпеки",
    "safety goggles": "захисні окуляри",
    "regulation": "правило",
    "safety": "безпека",
    "assembly line": "виробнича лінія",
    "repair": "ремонт",
    "malfunction": "несправність",
    "defect": "дефект",
    "screw": "гвинт",
    "drill": "дриль",
    "quality": "якість",
    "material": "матеріал",
    "safety shoes": "захисне взуття",
    "workshop": "майстерня",
    "moment": "момент",
    "time": "час",
    "machine": "машина",
    "part": "деталь",
    "conveyor belt": "конвеєр",
    "quota": "квота",
    "hour": "година",
    "shift operation": "змінна робота",
    "protective clothing": "захисний одяг",
    "tools": "інструменти",
    "helmet": "каска",
    "hammer": "молоток",
    "board": "дошка/дошка",
    "oak wood": "дубове дерево",
    "wood": "дерево",
    "processing": "обробка",
    "edges": "краї",
    "saw": "пила",
    "glue": "клей",
    "engine": "двигун",
    "brake": "гальмо",
    "tyre": "шина",
    "tool": "інструмент",
    "scaffolding": "риштування",
    "cement": "цемент",
    "plans": "плани",
    "ground floor": "перший поверх",
    "mortar": "розчин",
    "wall": "стіна",
    "construction site": "будівельний майданчик",
    "shovel": "лопата",
    "watering can": "лійка",
    "lawn mower": "газонокосарка",
    "soil": "ґрунт",
    "fence": "паркан",
    "patient": "пацієнт",
    "fever": "жар/температура",
    "medication": "ліки",
    "blood": "кров",
    "pain": "біль",
    "dizziness": "запаморочення",
    "doctor": "лікар",
    "ward round": "обхід лікаря",
    "daily menu": "денне меню",
    "dish": "страва",
    "meat": "м'ясо",
    "knife": "ніж",
    "frying pan": "сковорода",
    "saucepan": "каструля",
    "soup": "суп",
    "herbs": "трави",
    "sauce": "соус",
    "vegetables": "овочі",
    "cold room": "холодильна камера",
    "garlic": "часник",
    "head chef": "шеф-кухар",
    "starter": "закуска",
    "main course": "головна страва",
    "plate": "тарілка",
    "dessert": "десерт",
    "cutlery": "столові прибори",
    "glass": "склянка",
    "napkin": "серветка",
    "tablecloth": "скатертина",
    "tip": "чайові",
    "allergy": "алергія",
    "beer": "пиво",
    "menu": "меню",
    "bill": "рахунок",
    "till": "каса",
    "receipt": "чек",
    "loyalty card": "карта лояльності",
    "change": "решта",
    "small change": "дрібні монети",
    "shopping trolley": "візок",
    "shopping basket": "кошик",
    "goods": "товари",
    "offer": "пропозиція",
    "discount": "знижка",
    "bag": "пакет",
    "deposit": "застава",
    "frozen food": "заморожені продукти",
    "dairy products": "молочні продукти",
    "bakery": "хлібобулочні вироби",
    "expiry date": "термін придатності",
    "barcode": "штрих-код",
    "warehouse": "склад",
    "customer": "клієнт",
    "vacuum cleaner": "пилосос",
    "mop": "швабра",
    "cleaning agent": "засіб для прибирання",
    "bucket": "відро",
    "rag": "ганчірка",
    "broom": "мітла",
    "dust": "пил",
    "rubbish": "сміття",
    "rubbish bin": "сміттєвий кошик",
    "sponge": "губка",
    "washbasin": "умивальник",
    "stairwell": "сходова клітка",
    "floor": "підлога",
    "soap": "мило",
    "toilet paper": "туалетний папір",
    "dirt": "бруд",
    "meeting room": "переговорна кімната",
    "gloves": "рукавички",
    "scissors": "ножиці",
    "comb": "гребінець",
    "hair dryer": "фен",
    "paint": "фарба",
    "shampoo": "шампунь",
    "mirror": "дзеркало",
    "haircut": "стрижка",
    "gown": "пеньюар",
    "brush": "щітка",
    "towel": "рушник",
    "sprinkler system": "спринклерна система",
    "extinguishing system": "система пожежогасіння",
    "fire alarm system": "система пожежної сигналізації",
    "pipeline": "трубопровід",
    "pump": "насос",
    "valve": "клапан",
    "hydrant": "гідрант",
    "control unit": "пульт управління",
    "alarm": "тривога",
    "water connection": "підключення до водопроводу",
    "compressor": "компресор",
    "emergency generator": "аварійний генератор",
    "fire brigade connection": "підключення пожежної команди",
    "control cabinet": "шафа управління",
    "smoke detector": "димовий детектор",
    "gas detector": "газовий детектор",
    "motor gate valve": "моторний засувний клапан",
    "displays": "дисплеї",
    "lamps": "лампи",
    "warning signs": "попереджувальні знаки",
    "false alarm": "хибна тривога",
    "maintenance contract": "договір на обслуговування",
    "acceptance report": "акт прийому",
    "pressure drop": "падіння тиску",
    "leakage": "витік",
    "briefing / user instruction": "інструктаж",
    "customer service": "обслуговування клієнтів",
    "system failure": "відмова системи",
    "test report": "акт перевірки",
    "commissioning": "введення в експлуатацію",
    "instructions": "інструкції",
    "report": "звіт",
    "delivery": "доставка",
    "task": "завдання",
    "result": "результат",
    "improvement": "покращення",
    "wage": "заробітна плата",
    "contract": "договір",
    "training": "навчання",
    "order": "замовлення",
    "holiday request form": "заявка на відпустку",
    "overtime": "понаднормова робота",
    "payslip": "платіжна відомість",
    "notice / dismissal": "звільнення",
    "probationary period": "випробувальний термін",
    "employment contract": "трудовий договір",
    "induction / onboarding": "вступний інструктаж",
    "social insurance": "соціальне страхування",
    "emergency exit": "аварійний вихід",
    "safety briefing": "інструктаж з безпеки",
    "contact person": "контактна особа",
    "identity card": "посвідчення особи",
    "formal warning": "офіційне попередження",
    "works council": "профспілковий комітет",
    "pay rise": "підвищення зарплати",
    "sandpaper": "наждачний папір",
    "plane": "рубанок",
    "wall plug": "дюбель",
    "veneer wood": "шпоноване дерево",
    "clamp": "струбцина",
    "workbench": "верстак",
    "milling machine": "фрезерний верстат",
    "wood grain": "текстура дерева",
    "drawer": "ящик",
    "hinge": "завіса",
    "shelf / shelving unit": "полиця",
    "wardrobe / cabinet": "шафа",
    "coat of paint": "шар фарби",
    "wood stain": "морилка",
    "plywood": "фанера",
    "circular saw": "циркулярна пила",
    "jigsaw": "лобзик",
    "sander": "шліфувальна машина",
    "nail": "цвях",
    "clear varnish": "лак",
    "chisel": "стамеска",
    "wooden strip / moulding": "дерев'яна рейка",
    "fitting / hardware": "фурнітура",
    "trowel": "кельма",
    "concrete": "бетон",
    "brick": "цегла",
    "foundation": "фундамент",
    "screed": "стяжка",
    "plaster": "штукатурка",
    "roof": "дах",
    "site foreman": "виконроб",
    "concrete mixer": "бетономішалка",
    "straightedge / screed board": "правило",
    "fall protection": "захист від падіння",
    "insulation": "ізоляція",
    "reinforcement": "арматура",
    "formwork": "опалубка",
    "joint / grout line": "шов",
    "construction hoist": "будівельний підйомник",
    "steel": "сталь",
    "shell construction": "коробка будівлі",
    "protective film": "захисна плівка",
    "safety net": "захисна сітка",
    "mason's line": "мотузка муляра",
    "siphon": "сифон",
    "boiler": "котел",
    "thermostat": "термостат",
    "shower": "душ",
    "hot water": "гаряча вода",
    "pipe wrench": "трубний ключ",
    "sealing tape": "герметизувальна стрічка",
    "ball valve": "кульовий кран",
    "copper pipe": "мідна труба",
    "pipe pliers": "трубні плоскогубці",
    "burst pipe": "розрив труби",
    "pressure test": "гідравлічне випробування",
    "pipe sleeve": "муфта",
    "T-piece": "Т-подібний фітинг",
    "water filter": "водяний фільтр",
    "water pipe": "водопровідна труба",
    "soldering torch": "паяльна лампа",
    "water damage": "залив",
    "inspection / handover": "перевірка/приймання",
    "quote / estimate": "кошторис",
    "manifold": "колектор",
    "earthing": "заземлення",
    "resistor": "резистор",
    "lamp": "лампа",
    "fuse": "запобіжник",
    "socket": "розетка",
    "cable": "кабель",
    "short circuit": "коротке замикання",
    "wiring / cable run": "електропроводка",
    "wire strippers": "стриппер",
    "multimeter": "мультиметр",
    "fuse box": "розподільний щит",
    "voltage-free state": "знеструмлений стан",
    "conduit": "кабель-канал",
    "master electrician": "майстер-електрик",
    "terminal strip": "клемна рейка",
    "electricity meter": "лічильник електроенергії",
    "screwdriver": "викрутка",
    "oven": "духовка",
    "whisk": "вінчик",
    "ingredient": "інгредієнт",
    "apron": "фартух",
    "reservation": "бронювання",
    "tray": "піднос",
    "drink": "напій",
    "kitchen": "кухня",
    "warming cabinet": "шафа для підігріву",
    "chopping board": "обробна дошка",
    "fridge": "холодильник",
    "reorder": "поповнення запасів",
    "shift change": "зміна зміни",
    "serving hatch / food service": "вікно роздачі",
    "roast": "смаженина",
    "salt": "сіль",
    "deep fryer": "фритюрниця",
    "cooker / stove": "плита",
    "scales": "ваги",
    "delivery note": "накладна",
    "stocktaking": "інвентаризація",
    "complaint / return": "скарга/повернення",
    "exchange of goods": "обмін товарів",
    "complaint": "скарга",
    "till count": "підрахунок каси",
    "goods receipt": "приймання товару",
    "cash shortage": "нестача коштів",
    "return of goods": "повернення товару",
    "shift handover": "передача зміни",
    "fresh produce counter": "прилавок свіжих продуктів",
    "price label": "цінник",
    "queue": "черга",
    "special offer": "спеціальна пропозиція",
    "sticker / label": "наклейка",
    "credit note": "кредитна нота",
    "bottle return machine": "автомат прийому пляшок",
    "washing-up liquid": "засіб для миття посуду",
    "glass cleaner": "засіб для скла",
    "disinfectant": "дезінфектант",
    "wet floor sign": "знак мокра підлога",
    "descaler": "засіб від накипу",
    "mould remover": "засіб від плісняви",
    "all-purpose cleaner": "універсальний засіб",
    "radiator": "радіатор",
    "checklist": "контрольний список",
    "cleaning plan": "план прибирання",
    "substitute / cover": "замінник",
    "timesheet": "табель обліку",
    "lift / elevator": "ліфт",
    "deep clean": "генеральне прибирання",
    "routine cleaning": "планове прибирання",
    "bandage": "бинт",
    "syringe": "шприц",
    "infusion": "крапельниця",
    "wheelchair": "інвалідний візок",
    "blood pressure": "кров'яний тиск",
    "diagnosis": "діагноз",
    "hospital bed": "лікарняне ліжко",
    "laboratory": "лабораторія",
    "pulse": "пульс",
    "ECG": "ЕКГ",
    "handover (shift)": "передача чергування",
    "wound": "рана",
    "tablet / pill": "таблетка",
    "prescription": "рецепт",
    "emergency room / A&E": "приймальний покій",
    "blood draw": "забір крові",
    "catheter": "катетер",
    "oxygen saturation": "насичення киснем",
    "drip": "крапельниця",
    "nursing documentation": "медична документація",
    "folder": "папка",
    "stamp": "штамп",
    "signature": "підпис",
    "agenda": "порядок денний",
    "minutes": "протокол",
    "invoice / bill": "рахунок-фактура",
    "video conference": "відеоконференція",
    "password": "пароль",
    "department": "відділ",
    "manager / superior": "керівник",
    "office supplies": "канцелярські товари",
    "conference": "конференція",
    "network": "мережа",
    "lunch break": "обідня перерва",
    "gearbox": "коробка передач",
    "shock absorber": "амортизатор",
    "cooler": "радіатор охолодження",
    "drive belt": "привідний ремінь",
    "steering": "рульове управління",
    "windscreen wiper": "двірник",
    "headlight": "фара",
    "oil filter": "масляний фільтр",
    "battery": "акумулятор",
    "exhaust": "вихлопна труба",
    "spark plug": "свічка запалювання",
    "oil level": "рівень масла",
    "fault memory": "діагностична пам'ять",
    "service inspection": "технічне обслуговування",
    "vehicle ramp / lift": "автомобільний підйомник",
    "spare part": "запасна частина",
    "test drive": "тест-драйв",
    "brake hose": "гальмівний шланг",
    "air filter": "повітряний фільтр",
    "warranty": "гарантія",
    "oil pan": "піддон картера",
    "repair order": "замовлення на ремонт",
    "hedge": "жива огорожа",
    "compost": "компост",
    "hose": "шланг",
    "greenhouse": "теплиця",
    "flower bed": "клумба",
    "rake": "граблі",
    "weed": "бур'ян",
    "lawn": "газон",
    "plant": "рослина",
    "fertiliser": "добриво",
    "shed": "сарай",
    "hedge trimmer": "кущоріз",
    "shredder": "подрібнювач",
    "plant protection product": "засіб захисту рослин",
    "wheelbarrow": "тачка",
    "tree pruning": "обрізання дерев",
    "irrigation / watering": "полив",
    "spade": "штикова лопата",
    "chainsaw": "бензопила",
    "potting soil": "садовий ґрунт",
    "mulch": "мульча",
    "raised bed": "грядка",
    "homework": "домашнє завдання",
    "report card": "табель",
    "parents' evening": "батьківські збори",
    "timetable": "розклад",
    "chalk": "крейда",
    "curriculum": "навчальний план",
    "exercise book": "зошит",
    "pen / pencil": "ручка/олівець",
    "subject": "предмет",
    "grade": "оцінка",
    "class test": "контрольна робота",
    "school office": "канцелярія",
    "gym": "спортивна зала",
    "library": "бібліотека",
    "schoolyard": "шкільний двір",
    "group work": "групова робота",
    "dictation": "диктант",
    "essay": "твір",
    "staff meeting": "педагогічна нарада",
    "curling iron": "плойка",
    "hair straightener": "праска для волосся",
    "hairspray": "лак для волосся",
    "highlights": "мелірування",
    "conditioner": "кондиціонер",
    "parting": "проділ",
    "hairstyle": "зачіска",
    "gel": "гель",
    "hair colour / hair dye": "фарба для волосся",
    "perm": "хімічна завивка",
    "regrowth / roots": "відрослі корені",
    "processing time": "час витримки",
    "hair treatment": "маска для волосся",
    "scalp": "шкіра голови",
    "toning / tint": "тонування",
    "nape of the neck": "потилиця",
    "temple (of the head)": "скроня",
    "washbasin / shampoo bowl": "мийка",
    "haircut / cut": "стрижка",
    "bill / invoice": "рахунок",
    "visualisation": "візуалізація",
    "lab test": "лабораторний аналіз",
    "stmívač": "диммер",
    "svorkovnice": "клемна коробка",
    "vodováha": "рівень",
    "objímka na potrubí": "хомут для труби",
    "dieselová pumpa": "дизельний насос",
    "elektrická pumpa": "електричний насос",
    "mokrá stanice": "мокра станція",
    "suchá stanice": "суха станція",
    "nádoba / zásobník": "посудина/резервуар",
    "zpětný ventil / zpětná klapka": "зворотний клапан",
    "tlakoměr": "манометр",
    "plnící nádrž": "заповнювальний резервуар",
    "zpětná klapka": "зворотна засувка",
    "lapač kamenů": "пастка для каміння",
    "přetlakový ventil": "запобіжний клапан",
    "vytápění strojovny sprinklerů": "опалення насосної спринклерів",
    "vytápění nádrže / ohřev nádrže": "підігрів резервуара",
    "vytápění potrubí / ohřev potrubí": "обігрів трубопроводу",
    "mokrá ventilová stanice": "мокра клапанна станція",
    "poplachový zvon": "тривожний дзвін",
    "suchá ventilová stanice": "суха клапанна станція",
    "revizní šoupátko": "ревізійна засувка",
    "předstihová ventilová stanice": "клапанна станція попереднього спрацьовування",
    "tandemová ventilová stanice": "тандемна клапанна станція",
    "ventilová stanice na dálkové ovládání": "дистанційно керована клапанна станція",
    "rychlootvírač": "швидковідкривач",
    "dělící stanice": "розподільна станція",
    "systémový oddělovač": "системний роздільник",
    "siréna / houkačka": "сирена",
    "zábleskové čidlo / blikající maják": "проблисковий маяк",
    "čerpadlo pro zvýšení tlaku": "підвищувальний насос",
    "průtokový hlásič": "витратомір",
    "sprinkler": "спринклер",
    "dvojitý sprinkler": "подвійний спринклер",
    "sprinkler suchý": "сухий спринклер",
    "sprinkler testovací": "тестовий спринклер",
    "vypouštění": "злив",
    "odvodňovací jednotka": "дренажний пристрій",
    "nádrž na nemrznoucí směs": "бак антифризу",
    "tepelné čidlo": "тепловий сенсор",
    "tryska vodní clony": "форсунка водяної завіси",
    "ruční hlásič": "ручний сповіщувач",
    "dávkovací systém": "дозувальна система",
    "nádrž pro antikorozní ochranu": "бак антикорозійного захисту",
    "hydrantové zařízení": "гідрантна установка",
    "rychloodvzdušňovač": "швидкий повітровідводчик",
    "monitorovací centrála": "центр моніторингу",
    "zásobní nádrž pěnidla": "резервуар піноутворювача",
    "Venturiho příměšovadlo": "змішувач Вентурі",
    "tlakový přiměšovač": "пропорціонер тиску",
    "pěnové čerpadlo": "піновий насос",
    "generátor pěny": "пінний генератор",
    "pěnové vodní dělo": "пінний монітор",
    "zkouška příměsi pěnidla": "перевірка змішування піноутворювача",
    "aktualizace softwaru": "оновлення програмного забезпечення",
    "rozhraní / centrální síť": "інтерфейс/центральна мережа",
    "skupiny hlásičів": "групи сповіщувачів",
    "signální smyčky": "сигнальні петлі",
    "baterie / akumulátory": "акумулятори",
    "externí napájení": "зовнішнє живлення",
    "protokolová tiskárna": "принтер протоколів",
    "přepínač revize": "перемикач ревізії",
    "body hlášení": "точки оповіщення",
    "tablo rozmístění": "схема розміщення",
    "indikační světlo": "індикаторний світловий сигнал",
    "značení úniková cesta": "позначення евакуаційного шляху",
    "ovládání hlavního hlásiče": "управління головним сповіщувачем",
    "sklad klíčů hasičů": "ящик ключів пожежної служби",
    "hasičský zobrazovací panel": "дисплейна панель пожежної служби",
    "průvodky pro hasiče": "супровідні картки для пожежників",
    "ovládací panel hasičů": "панель управління пожежної служби",
    "odpojovací zařízení": "роз'єднувальний пристрій",
    "automatická přenosová ústředna": "автоматична перетворювальна станція",
    "přenášené kanály": "передавані канали",
    "přenos hlášení": "передача повідомлень",
    "optický alarm": "оптична тривога",
    "zvukový alarm": "звукова тривога",
    "alarmová řídicí jednotka / poplachová řídicí jednotka": "блок управління тривогою",
    "tlačítko požárního poplachu": "кнопка пожежної тривоги",
    "ruční spuštění": "ручний запуск",
    "tlačítko zastavení": "кнопка зупинки",
    "tlačítko dodatečného zaplavení": "кнопка додаткового затоплення",
    "tepelný detektor": "тепловий детектор",
    "multisenzor": "мультидатчик",
    "snímač požárního plynu": "датчик пожежного газу",
    "výstražné zařízení CO2": "пристрій сигналізації CO2",
    "detektor plamene": "детектор полум'я",
    "detektor jisker": "детектор іскор",
    "prvek detekce požáru": "елемент пожежного виявлення",
    "systém nasávání kouře": "система аспірації диму",
    "detektor kanálu": "канальний детектор",
    "detektor bypassu": "обхідний детектор",
    "spojka smyčky": "з'єднувач петлі",
    "plynová hlásicí centrála": "газова сигнальна централь",
    "přehled linek hlášení plynu": "огляд ліній газового сповіщення",
    "plynem hašené sektory": "сектори газового гасіння",
    "monitorování hasicích systémů": "моніторинг систем пожежогасіння",
    "alarmový tlakový spínač": "аварійний перемикач тиску",
    "spouštění": "запуск",
    "ústředna pro dvojité sprinklery": "централь для подвійних спринклерів",
    "centrála řízení dveří": "централь управління дверима",
    "uzamykací zařízení": "блокувальний пристрій",
    "přídržný magnet": "утримуючий магніт",
    "vypnutí klimatizace": "відключення кондиціонера",
    "vypnutí strojů": "відключення машин",
    "automatický hasicí systém": "автоматична система пожежогасіння",
    "topná páska": "нагрівальна стрічка",
    "topný okruh": "нагрівальний контур",
    "vstupní modul": "вхідний модуль",
    "výstupní modul": "вихідний модуль",
    "lahvová baterie": "батарея балонів",
    "láhve s hasivem": "балони з вогнегасною речовиною",
    "sběrné potrubí": "збірний трубопровід",
    "vážicí zařízení": "зважувальний пристрій",
    "kontrolní lahve": "контрольні балони",
    "rozdělovač / rozdělovací potrubí": "розподільник",
    "bezpečnostní ventil": "запобіжний клапан",
    "sekční ventil": "секційний клапан",
    "směrový ventil": "направляючий клапан",
    "kompenzátor tlaku": "компенсатор тиску",
    "spouštěcí hmotnost": "пускова вага",
    "blokovací zařízení": "блокувальний пристрій",
    "zpožďovací zařízení": "пристрій затримки",
    "střídavý zpětný ventil": "змінний зворотний клапан",
    "lapač nečistot": "фільтр-грязьовик",
    "ochrana proti úniku plynu": "захист від витоку газу",
    "kabelový systém / lankový systém": "кабельна/тросова система",
    "tepelný izolátor": "тепловий ізолятор",
    "pneumatický tepelný senzor": "пневматичний тепловий датчик",
    "siréna / makrofon": "сирена/мегафон",
    "pneumatické odblokování dveří": "пневматичне розблокування дверей",
    "elektrická houkačka": "електрична сирена",
    "nízkotlaká nádrž": "низькотисковий резервуар",
    "chladicí jednotka": "охолоджувальний пристрій",
    "plnicí zařízení": "заправний пристрій",
    "bezpečnostní uzavírací ventil": "захисний запірний клапан",
    "dvojitý pojistný ventil": "подвійний запобіжний клапан",
    "elektrický rozvaděč": "електричний розподільний щит",
    "hlavní uzavírací ventil": "головний запірний клапан",
    "předstihový řídicí ventil": "випереджаючий управляючий клапан",
    "odorizační zařízení": "одорант-пристрій",
    "jednotka servoventilu": "блок сервоклапана",
    "odvzdušňovací ventil": "повітровідводчик",
    "excentrická klapka": "ексцентрична засувка",
    "dveře a brány": "двері та ворота",
    "elektrická řídicí jednotka": "електричний блок управління",
    "dodávka energie / napájení": "живлення/подача енергії",
    "akustický poplašný systém": "акустична система тривоги",
    "optický poplašný systém": "оптична система тривоги",
    "skupiny hlásičů": "групи сповіщувачів",
}

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    out = []
    in_questions = False
    in_fill = False
    added = 0
    already = 0

    for line in lines:
        if 'export const QUESTIONS' in line:
            in_questions = True
            in_fill = False
        elif 'export const FILL_QUESTIONS' in line:
            in_questions = False
            in_fill = False  # FILL handled by separate script

        if (in_questions) and 'translationEn:' in line and 'translationUk:' not in line:
            # Extract translationEn value
            m = re.search(r'translationEn:\s*"([^"]+)"', line)
            if m:
                en_val = m.group(1)
                uk_val = Q_UK.get(en_val)
                if uk_val:
                    # Insert translationUk before profession:
                    new_line = re.sub(
                        r'(translationPl:\s*"[^"]*",)',
                        lambda mo: mo.group(1) + f' translationUk: "{uk_val}",',
                        line
                    )
                    if new_line != line:
                        out.append(new_line)
                        added += 1
                        continue
        elif 'translationUk:' in line and in_questions:
            already += 1

        out.append(line)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(out)

    print(f"QUESTIONS: added {added} translationUk entries, {already} already present")

if __name__ == '__main__':
    process_file('/Users/simonaweinertova/germanllama/src/game/vocabularyData.ts')
